#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

try {
const BASE = 'https://www.scoopychatt.com';
const distDir = path.join(process.cwd(), 'dist', 'apps', 'web');
const templatePath = path.join(distDir, 'index.html');

if (!fs.existsSync(templatePath)) {
  console.log('SEO inject: dist/apps/web/index.html not found, skipping (build cache active)');
  process.exit(0);
}

const template = fs.readFileSync(templatePath, 'utf-8');

const BODY_CLOSE = '<' + '/body>';
const DIV_CLOSE = '<' + '/div>';

// Static content blocks for key non-location pages
const SC = {
  '/press': "<h1>Scoopy Doo in the News: Chattanooga's Largest Pet Waste Removal Company</h1><p>Scoopy Doo LLC is the largest and fastest-growing pet waste removal company in the Chattanooga, TN area, serving more than 150 clients with 90 five-star reviews across Chattanooga and North Georgia. In June 2026, Scoopy Doo was featured by the Chattanoogan, and in July 2026 by WDEF News 12.</p><h2>Featured in the Chattanoogan</h2><p>14-Year-Old Entrepreneur Builds Chattanooga's Largest Pet Waste Removal Company In Under A Year. Founder Leighton Carter grew Scoopy Doo LLC from a single customer to more than 150 active clients in under a year, with her dad Brandon supporting her along the way, serving dog owners, HOAs, apartment communities, and commercial properties across Chattanooga and North Georgia. <a href='https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx'>Read the full article on Chattanoogan.com</a>.</p><h2>Featured on WDEF News 12</h2><p>On July 2, 2026, WDEF News 12 featured Scoopy Doo LLC, the father and daughter pet waste removal company. Fourteen-year-old Leighton Carter started the company with help from her dad, Brandon, and the family now runs Scoopy Doo full-time, serving more than 150 customers across the Chattanooga area with a team of three. Scoopy Doo offers weekly, bi-weekly, and twice-a-week yard cleanings. <a href='https://www.wdef.com/scoopy-doo-llc-pet-waste-removal/'>Watch the story on WDEF.com</a>.</p><h2>Press and Media Inquiries</h2><p>For press and media inquiries, contact Scoopy Doo at info@scoopychatt.com.</p>",
  '/services': "<h1>Pet Waste Removal Services in Chattanooga, TN</h1><p>Scoopy Doo offers professional pet waste removal for homes, businesses, and HOAs in Chattanooga TN and North Georgia. All services include on-the-way texts and gate photo confirmation. No contracts required.</p><h2>Weekly Dog Poop Removal</h2><p>Most popular service. A technician visits once per week, removes all dog waste, texts on the way, and sends a gate photo after each visit. Pricing based on yard size and number of dogs. Free quote at scoopychatt.com/quote.</p><h2>Every-Other-Week Pooper Scooper Service</h2><p>Every two weeks. Ideal for smaller yards or fewer dogs.</p><h2>One-Time Yard Cleanup</h2><p>Single deep-clean visit. Perfect for spring cleanup, before a party, or as a first visit.</p><h2>Commercial Pet Waste Removal</h2><p>Regular scheduled service for apartment complexes, dog parks, and businesses in Chattanooga and North Georgia.</p><h2>HOA Common Area Cleanup</h2><p>Scheduled pet waste removal for shared green spaces and common areas throughout the Chattanooga metro area.</p>",
  '/faq': "<h1>Frequently Asked Questions About Dog Poop Removal in Chattanooga</h1><h2>How much does dog poop removal cost in Chattanooga?</h2><p>Scoopy Doo weekly service starts at $20 per visit for one dog. Twice-weekly service is $18 per visit and every-other-week service starts at $33 per visit. One-time yard cleanups start at $85. All pricing is based on yard size and number of dogs -- every quote is free and personalized at scoopychatt.com/quoterequest. There are no contracts.</p><h2>Does Scoopy Doo serve North Georgia?</h2><p>Yes. Scoopy Doo serves Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA in addition to Chattanooga, Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, Cleveland, East Ridge, and Lookout Mountain TN. North Georgia customers pay the same rates as Tennessee locations.</p><h2>What happens on each visit?</h2><p>You receive a text when your technician is on the way. The technician searches the entire yard in a grid pattern. All waste is double-bagged and hauled fully off your property. After every visit you receive a gate photo confirmation so you know the yard is clean and the gate is secured.</p><h2>Is there a contract?</h2><p>No contracts, ever. You can start, pause, or cancel service at any time. There are no cancellation fees or minimum commitments.</p><h2>How often should I have my yard cleaned?</h2><p>Weekly is the gold standard for homes with one or two dogs and prevents waste from building up and damaging grass. Every-other-week works well for smaller yards or single-dog households. One-time cleanups are ideal for spring cleaning, before a party, or before listing a home for sale.</p><h2>Do I need to be home during service?</h2><p>No. Most Scoopy Doo customers are not home during service. Just make sure gate access is available. You will receive an on-the-way text and a gate photo confirming the visit is complete.</p><h2>How quickly can service start?</h2><p>Most new customers start within 2 to 5 days of requesting a quote. Request a free quote at scoopychatt.com/quoterequest and Scoopy Doo responds the same day.</p><h2>Do you charge extra for multiple dogs?</h2><p>Yes, there is a small additional fee per extra dog to account for the additional waste and time. Your free quote will include the exact price for your yard size and dog count.</p><h2>Are you insured?</h2><p>Yes. Scoopy Doo is fully insured on every visit.</p><h2>What is a one-time cleanup?</h2><p>A one-time deep-clean visit removes all accumulated waste. It is ideal for spring cleaning, before a party, before listing a home, or as a first visit before starting regular service. One-time cleanups start at $85 and can be booked at scoopychatt.com/one-time-cleanup.</p>",
  '/service-areas': "<h1>Pet Waste Removal Service Areas - Chattanooga TN and North Georgia</h1><p>Scoopy Doo serves Chattanooga, TN and the surrounding metro area including North Georgia communities. We run regular routes throughout the region and most new customers can start within 2-5 days of a free quote.</p><h2>Tennessee Service Areas</h2><ul><li>Chattanooga, TN</li><li>Hixson, TN</li><li>Red Bank, TN</li><li>Signal Mountain, TN</li><li>Lookout Mountain, TN</li><li>Soddy-Daisy, TN</li><li>Ooltewah, TN</li><li>East Brainerd, TN</li><li>East Ridge, TN</li><li>Collegedale, TN</li><li>Apison, TN</li><li>Cleveland, TN</li><li>Highland Park (Chattanooga), TN</li><li>Downtown Chattanooga, TN</li></ul><h2>North Georgia Service Areas</h2><ul><li>Ringgold, GA</li><li>Rossville, GA</li><li>Fort Oglethorpe, GA</li><li>Flintstone, GA</li></ul><p>All North Georgia locations are served at the same rates as Tennessee. No extra fees for crossing the state line.</p>",
  '/how-it-works': "<h1>How Scoopy Doo Pet Waste Removal Works</h1><p>Scoopy Doo makes professional dog poop removal simple. Request a free quote, we respond the same day, and most new customers start within 2-5 days.</p><h2>Step 1: Get a Free Quote</h2><p>Request a quote at scoopychatt.com/quoterequest. Tell us your yard size, number of dogs, and preferred service frequency. We respond the same day with exact pricing.</p><h2>Step 2: We Come to You</h2><p>On your scheduled day, you receive a text when your technician is on the way. No need to be home. Just make sure we have gate access.</p><h2>Step 3: Complete Yard Cleanup</h2><p>The technician searches the entire yard using a grid-pattern approach to make sure nothing is missed. All waste is double-bagged and hauled away from the property entirely.</p><h2>Step 4: Gate Photo Confirmation</h2><p>After every visit, your gate is secured and a photo is sent to confirm the job is done. You know your yard is clean without having to check yourself.</p>",
  '/about': "<h1>About Scoopy Doo Pet Waste Removal - Chattanooga, TN</h1><p>Scoopy Doo LLC is a locally owned pet waste removal company serving Chattanooga, TN and North Georgia. We are a father-daughter team committed to reliable, professional service with real accountability - on-the-way texts, gate photo confirmation, and waste hauled fully off your property every visit.</p><p>Scoopy Doo LLC was founded by Leighton Carter, who started the business at 14 years old with a single customer and grew it into Chattanooga's largest pet waste removal company in under a year, with her dad Brandon supporting her every step of the way. Their story has been featured by the Chattanoogan and WDEF News 12.</p><p>We serve residential homes, HOA communities, apartment complexes, and commercial properties throughout the Chattanooga metro area including North Georgia communities in Catoosa and Walker counties. No contracts, ever.</p><p>Scoopy Doo LLC is accredited by the Better Business Bureau (BBB). See the Scoopy Doo BBB Business Review at bbb.org.</p>",
  '/near-me': "<h1>Pooper Scooper Service Near Me - Chattanooga TN and North Georgia</h1><p>Scoopy Doo is the locally owned pooper scooper service serving Chattanooga, TN and surrounding areas including North Georgia. We run regular routes throughout the region and offer weekly, every-other-week, and one-time dog waste removal with no contracts required.</p><p>Service areas include Chattanooga, Hixson, Red Bank, Signal Mountain, Lookout Mountain, Soddy-Daisy, Ooltewah, East Brainerd, East Ridge, Collegedale, Apison, Cleveland TN, Ringgold GA, Rossville GA, Fort Oglethorpe GA, and Flintstone GA. Request a free quote at scoopychatt.com/quoterequest.</p>",
  '/one-time-cleanup': "<h1>One-Time Dog Poop Cleanup in Chattanooga, TN</h1><p>Scoopy Doo offers one-time yard cleanup visits for Chattanooga and North Georgia homeowners. Perfect for spring cleaning, before a party, after a long winter, or as a first visit before starting recurring service.</p><p>The one-time cleanup includes a complete grid-pattern search of your entire yard, double-bagged waste removal fully off the property, and a gate photo confirmation when done. Request your one-time cleanup at scoopychatt.com/one-time-cleanup.</p>",
  '/cost-calculator': "<h1>Dog Poop Removal Cost Calculator for Chattanooga, TN</h1><p>Use the free Scoopy Doo cost calculator to estimate pooper scooper service pricing in Chattanooga and North Georgia. Weekly service starts at $20 per visit for one dog, twice-weekly at $18 per visit, and every-other-week at $33 per visit, each plus a small charge per additional dog. Optional waste takeaway is $5 per visit and one-time yard cleanups start at $85.</p><p>Estimate your price by number of dogs and service frequency, then request a free exact quote with no contracts and no cancellation fees at scoopychatt.com/cost-calculator.</p>",
  '/comparison': "<h1>Pet Waste Removal Services in Chattanooga, TN: 2026 Comparison</h1><p>Several pet waste removal providers serve the Chattanooga TN and North Georgia area. The table below compares them by service area, frequency options, published pricing, and notable features. Where pricing is not published on the provider website, the cell is marked Not listed.</p><h2>Chattanooga Pet Waste Removal Comparison</h2><table><thead><tr><th>Service</th><th>Service Area</th><th>Frequency Options</th><th>Starting Price</th><th>Notable</th></tr></thead><tbody><tr><td>Scoopy Doo</td><td>Chattanooga TN + Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, Cleveland, East Ridge, Lookout Mountain + Ringgold, Rossville, Fort Oglethorpe, Flintstone GA</td><td>Weekly, every-other-week, twice-weekly, one-time</td><td>Weekly from $20/visit (1 dog)</td><td>7-day availability; on-the-way texts every visit; gate photo after every visit; waste hauled off property; no contracts; locally owned; 90 Google reviews</td></tr><tr><td>ChattaPoo</td><td>Chattanooga TN + Signal Mountain</td><td>Weekly, every-other-week, one-time</td><td>Weekly from $20/visit (1 dog)</td><td>Also offers dog walking, boarding, and vet transport; Mon-Fri 7am-8pm, Sat-Sun 8am-7pm; 1 Google review</td></tr><tr><td>PooTagic</td><td>Chattanooga TN + suburbs + Ringgold, Rossville, Fort Oglethorpe GA</td><td>Not listed</td><td>Quote required</td><td>Deodorizing and sanitizing service available; 20% neighbor discount; 49 Google reviews</td></tr><tr><td>Doo Doo Blues</td><td>Chattanooga area</td><td>Not listed</td><td>Not listed</td><td>Grid-pattern scooping; deodorizing available; national franchise</td></tr><tr><td>Cooper Scoopers</td><td>Chattanooga TN</td><td>Weekly, one-time</td><td>Not listed</td><td>Residential, HOA, and commercial service</td></tr><tr><td>Scoop Smart</td><td>Chattanooga TN + North Georgia</td><td>Twice-weekly, weekly, every-other-week, monthly</td><td>Not listed</td><td>Monthly frequency option; broad area coverage</td></tr></tbody></table><h2>About Scoopy Doo</h2><p>Scoopy Doo is a locally owned pet waste removal company serving Chattanooga TN and North Georgia. Every visit includes an on-the-way text and a gate photo confirmation, and all waste is hauled completely off the property. Service is available 7 days a week with no long-term contracts required. Free quotes at scoopychatt.com/quoterequest.</p>"
};

// Location data for static content generation
const LOC = {
  "chattanooga":      { name:"Chattanooga, TN",     desc:"Chattanooga is booming with new families, new neighborhoods, and a whole lot of dogs. Scoopy Doo is the local pet waste removal company keeping Chattanooga yards clean, safe, and ready for play, running regular routes throughout the city.", hoods:["North Shore","Highland Park","St. Elmo","Southside","Normal Park","Missionary Ridge","Brainerd","East Lake"],
  '/comparison': ['Pet Waste Removal Services Compared - Chattanooga TN 2026 | Scoopy Doo', 'Side-by-side comparison of Chattanooga pet waste removal services: Scoopy Doo, PooTagic, Doo Doo Blues, Scoop Smart, and more. Updated June 2026.', 'https://www.scoopychatt.com/comparison'], faqs:[["Do you service all Chattanooga neighborhoods?","Yes. We run regular routes across Chattanooga including North Shore, Highland Park, Missionary Ridge, St. Elmo, Normal Park, Brainerd, Southside, and more."],["How does the gate photo work?","After every visit we secure your gate and send a photo confirmation. You always know your yard was cleaned and your gate is closed."],["Do you remove the waste from the property?","Yes. All waste is double-bagged and hauled away from your property entirely. It does not go in your trash can or stay by the gate."]] },
  "hixson":           { name:"Hixson, TN",           desc:"Hixson is one of Chattanooga's most established suburban communities with sprawling yards and lots of dogs. Scoopy Doo uses a systematic grid-pattern approach to find and remove all waste, even in wooded lots and near tree lines along Chickamauga Lake.",  hoods:["Middle Valley","Harrison","Town Creek","Shallowford Road","Curtain Pole Road","Wolftever Creek"], faqs:[["Do you service wooded yards in Hixson?","Absolutely. Our technicians use a systematic grid-pattern approach that covers your entire yard, including wooded sections and areas near tree lines."],["Do you remove the waste or leave bags at the gate?","We double-bag all waste and haul it away entirely. It is never left by your gate or in your trash can."],["Is there a contract?","No contracts, ever. You can start, pause, or cancel service at any time."]] },
  "red-bank":         { name:"Red Bank, TN",          desc:"Red Bank is a tight-knit city inside greater Chattanooga where neighbors know each other and community standards matter. Scoopy Doo serves Red Bank homeowners with reliable weekly pet waste removal, on-the-way texts, and gate photo confirmation after every visit.", hoods:["Red Bank proper","Dayton Pike area","Signal Mountain Road corridor","Ashland Terrace","Scenic View area"], faqs:[["Do you service all of Red Bank?","Yes. We service all Red Bank neighborhoods including areas along Dayton Pike, Signal Mountain Road, and surrounding residential streets."],["How often should I have service?","For one or two dogs, weekly service is the most popular option. It prevents waste from accumulating and keeps your yard clean and odor-free."],["Is your service reliable in winter?","Yes. We provide year-round service in Red Bank regardless of weather. We show up rain, cold, or shine."]] },
  "signal-mountain":  { name:"Signal Mountain, TN",   desc:"Signal Mountain properties have beautiful terrain and that same terrain makes pet waste cleanup genuinely difficult. Scoopy Doo is experienced with Signal Mountain yards - wooded lots, steep grades, and extensive ground cover - and uses a thorough grid-pattern approach to find and remove everything.", hoods:["Signal Mountain proper","Waldens Ridge","Signal Crest","James Boulevard corridor","Taft Highway area"], faqs:[["Do you service large or steeply graded properties?","Yes. Our technicians are experienced with Signal Mountain terrain including wooded sections, sloped yards, and large properties."],["Do you remove waste from the property?","Yes. We remove all waste from the property entirely and haul it away in our vehicle. We never leave bags at your gate."],["Is service available year-round?","Yes. We provide year-round service on Signal Mountain regardless of weather conditions."]] },
  "ooltewah":         { name:"Ooltewah, TN",          desc:"Ooltewah is one of the fastest-growing communities in the Chattanooga region with master-planned neighborhoods, active HOAs, and high standards for community appearance. Scoopy Doo helps Ooltewah families and HOA boards keep shared spaces and private yards consistently clean. We provide dependable dog poop pickup and pooper scooper service near Ooltewah, TN.", hoods:["Cambridge Square","Hamilton on Hunter","Snow Hill","Georgetown area","Windstone"], faqs:[["Do you serve HOAs and subdivisions in Ooltewah?","Yes. We service HOA common areas, green spaces, and dog-walking paths in Ooltewah subdivisions. We can work directly with HOA boards on scheduling and invoicing."],["Can Ooltewah service help avoid HOA violations?","Absolutely. Consistent professional cleanup is the most reliable way to stay compliant with HOA pet waste rules."],["Do you service Georgetown and Snow Hill areas?","Yes. We cover all major Ooltewah neighborhoods including Cambridge Square, Hamilton on Hunter, Snow Hill, Georgetown, and surrounding areas."]] },
  "east-brainerd":    { name:"East Brainerd, TN",     desc:"East Brainerd is one of Chattanooga's busiest suburban corridors - full of growing families, newer subdivisions, and busy schedules that leave no time for yard cleanup. Scoopy Doo keeps East Brainerd yards consistently clean with on-the-way texts and gate photo confirmation every visit.", hoods:["Gunbarrel Road area","Ooltewah-Georgetown Road","Camp Jordan vicinity","Jenkins Road corridor","East Brainerd Road subdivisions"], faqs:[["Do you service the subdivisions along Gunbarrel Road?","Yes. We have regular routes throughout East Brainerd including neighborhoods along Gunbarrel Road, Ooltewah-Georgetown Road, Jenkins Road, and surrounding areas."],["How do I get started?","Request a free quote online. We respond the same day and most new East Brainerd customers can start within 2-5 days."],["Do you handle overgrown yard cleanups?","Yes. If your yard has not been cleaned in a while, we offer one-time deep-clean visits to start fresh before setting up recurring service."]] },
  "soddy-daisy":      { name:"Soddy-Daisy, TN",       desc:"Soddy-Daisy stretches along beautiful Chickamauga Lake with a mix of lakefront homes and inland neighborhoods. Scoopy Doo provides consistent reliable pet waste pickup that keeps your yard clean and the lake healthy, serving Soddy-Daisy with regular routes and on-the-way texts every visit.", hoods:["Soddy-Daisy proper","Sequoyah Drive area","Chickamauga Lake shoreline","Dayton Pike corridor","Zion Hill Road area","Falling Water area"], faqs:[["Do you service lakefront properties in Soddy-Daisy?","Yes. We service lakefront and lake-view properties throughout Soddy-Daisy. Waterfront properties are one of the most important places to have consistent pet waste removal because of runoff."],["How does dog waste affect Chickamauga Lake?","Dog waste contains bacteria and pathogens that wash into the lake during rain. Regular professional cleanup significantly reduces contamination that reaches the water from your property."],["Can you service docks or lakeside areas?","Yes. We can clean yard areas leading to docks and waterfront access points, the areas closest to the water where cleanup matters most."]] },
  "east-ridge":       { name:"East Ridge, TN",         desc:"East Ridge sits on the Tennessee-Georgia border with a proud residential community that takes care of its neighborhoods. Scoopy Doo runs regular routes through East Ridge, keeping yards clean for families who want more time for the things they actually enjoy.", hoods:["Ringgold Road area","Cloud Springs Road","McBrien Road area","Bennett Road corridor","Spring Creek area"], faqs:[["Do you service East Ridge neighborhoods near the Georgia line?","Yes. East Ridge is well within our service area. We run regular routes throughout East Ridge including neighborhoods near the Georgia border."],["Can I get a one-time cleanup before starting regular service?","Yes. Many new customers start with a one-time deep clean to get the yard back to baseline, then move to weekly service."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all scooping tools between every yard to prevent the spread of bacteria and parasites."]] },
  "lookout-mountain": { name:"Lookout Mountain, TN",  desc:"Lookout Mountain is one of the most distinctive communities in the region with historic homes, sweeping properties, and terrain that makes DIY pet waste cleanup a real challenge. Scoopy Doo navigates the terrain carefully to deliver a thorough cleanup every visit.", hoods:["Lookout Mountain proper","Sunset Drive corridor","Ochs Highway area","Scenic Highway section","Bragg Avenue area"], faqs:[["Do you service Lookout Mountain properties?","Yes. We service Lookout Mountain properties including homes along Sunset Drive, Ochs Highway, Scenic Highway, and throughout the community."],["Can you handle terraced or steeply graded yards?","Yes. Our technicians are careful and thorough on terraced and sloped properties. We take the time to cover difficult terrain."],["How do you access gated properties?","Many Lookout Mountain clients provide a gate code at sign-up. We use it for every visit, close the gate after cleaning, and send a photo confirmation."]] },
  "ringgold":         { name:"Ringgold, GA",           desc:"Ringgold is the heart of Catoosa County about 15 miles south of Chattanooga. Scoopy Doo proudly serves Ringgold homeowners with professional pet waste removal, regular North Georgia routes, and no extra fees for Georgia locations. We handle dog poop removal across Ringgold and North Georgia (Catoosa and Walker counties) at no extra charge.", hoods:["Ringgold proper","Catoosa County subdivisions","Graysville Road area","Cloud Springs Road","Battlefield Parkway corridor"], faqs:[["Do you service Ringgold, GA?","Yes. Ringgold is one of our core service areas. We run regular routes throughout Ringgold and Catoosa County and do not charge extra for North Georgia locations."],["Is there any extra charge for Georgia locations?","No. Our pricing for Ringgold is the same as our Tennessee locations, based on yard size and number of dogs."],["How quickly can you start service?","Most Ringgold customers can be added to a route within 2-5 days of requesting a quote."]] },
  "rossville":        { name:"Rossville, GA",          desc:"Rossville sits right on the Tennessee-Georgia border moments from Chattanooga with established residential neighborhoods and a community that takes care of its properties. Scoopy Doo runs regular North Georgia routes and serves Rossville homeowners with reliable professional service.", hoods:["Rossville proper","McFarland Avenue area","Chickamauga Avenue corridor","Alabama Avenue area","North Georgia border neighborhoods"], faqs:[["Do you service Rossville, GA?","Yes. Rossville is within our North Georgia service area. We run regular routes and do not charge additional fees for Georgia locations."],["Do you service homes with multiple large dogs?","Absolutely. Multi-dog households are some of our best customers. Our pricing scales reasonably for additional dogs and we cover the full yard every visit."],["Do you remove the waste from the property?","Yes. We double-bag all waste and haul it away entirely. It does not go in your trash can or stay by your gate."]] },
  "fort-oglethorpe":  { name:"Fort Oglethorpe, GA",   desc:"Fort Oglethorpe is one of the fastest-growing cities in North Georgia with new subdivisions, active HOAs, and families who want their neighborhoods to look great. Scoopy Doo serves Fort Oglethorpe with professional weekly and every-other-week pet waste removal and HOA common area service.", hoods:["Fort Oglethorpe proper","Battlefield Parkway corridor","Barnhardt Road area","Chickamauga Battlefield vicinity","LaFayette Road area","Parker Drive corridor"], faqs:[["Do you service Fort Oglethorpe, GA?","Yes. Fort Oglethorpe is within our regular North Georgia service area. We run established routes and do not charge extra for Catoosa County locations."],["Do you work with HOAs in Fort Oglethorpe?","Yes. We service HOA common areas, dog-walking paths, and pet waste stations throughout Fort Oglethorpe."],["Do you service newer Fort Oglethorpe subdivisions?","Yes. We actively service newer developments along Battlefield Parkway, Barnhardt Road, LaFayette Road, and other growing corridors."]] },
  "cleveland":        { name:"Cleveland, TN",          desc:"Cleveland is the heart of Bradley County and one of the fastest-growing cities in the region. Scoopy Doo serves Cleveland families with professional pet waste removal - on-the-way texts, gate photo confirmation, and waste hauled fully off your property every visit. Regular Bradley County routes with no extra fees.", hoods:["Cleveland proper","Lee University area","North Cleveland","White Oak area","Blythe Ferry Road corridor","Westside"], faqs:[["Do you service Cleveland, TN?","Yes. Cleveland is within our service area. We run routes throughout Cleveland and Bradley County and do not charge extra for distance from Chattanooga."],["How quickly can I start service?","Most Cleveland customers can be added to a route within 2-5 days of requesting a quote. We respond the same day."],["Do you haul the waste away?","Yes. We haul all waste fully off your property, double-bagged and removed in our vehicle. It does not go in your trash can or stay by the gate."]] },
  "apison":           { name:"Apison, TN",             desc:"Apison is one of Hamilton County's fast-growing communities with newer residential developments and larger lots. Scoopy Doo handles the whole yard every visit using a grid-pattern approach, making professional cleanup especially valuable for larger properties with multiple dogs.", hoods:["Apison Pike corridor","Standifer Gap Road area","Hamilton County rural east","Harrison vicinity","East Hamilton corridor"], faqs:[["Do you service Apison, TN?","Yes. Apison is within our East Hamilton County service area. We run regular routes and can typically start new customers within 2-5 days."],["Do you offer pricing for multiple dogs?","Yes. Our pricing scales affordably for households with multiple dogs. Request a free quote for your exact pricing."],["Can you handle larger lots?","Absolutely. We service a range of property sizes including larger lots typical in the Apison area and use a grid approach to cover every section."]] },
  "collegedale":      { name:"Collegedale, TN",        desc:"Collegedale is a small community-focused city east of Chattanooga with well-maintained neighborhoods and high standards for appearance. Scoopy Doo serves Collegedale families with reliable weekly and every-other-week pet waste removal with consistent scheduling and no hidden fees.", hoods:["Collegedale proper","Southern Adventist University area","McDonald Road corridor","Apison Pike vicinity","East Hamilton corridor"], faqs:[["Do you service Collegedale, TN?","Yes. Collegedale is within our East Hamilton County service area. We run regular routes and do not charge extra for East Hamilton County locations."],["Are there any hidden fees?","No hidden fees. Our pricing is based on yard size and number of dogs. No fuel surcharges, no seasonal fees."],["How consistent is the schedule?","You are assigned a regular day and we show up on that day every week or every-other-week. You get an on-the-way text before each visit."]] },
  "highland-park":    { name:"Highland Park, TN",      desc:"Highland Park is one of Chattanooga's most vibrant historic neighborhoods with tree-lined streets, revitalized bungalows, and neighbors who care about their blocks. Scoopy Doo runs regular Chattanooga routes through Highland Park, providing reliable urban yard cleanup.", hoods:["Highland Park proper","McCallie Avenue corridor","Third Street area","Dodds Avenue vicinity","Glass Street area","Orchard Knob nearby"], faqs:[["Do you service small urban yards in Highland Park?","Yes. We service yards of all sizes including the smaller urban lots typical in Highland Park. Smaller yards often mean waste is more concentrated and more important to keep clean consistently."],["How often should I have service?","For most Highland Park households with one or two dogs, weekly service is the best choice. Smaller yards fill up quickly and weekly pickup keeps odor and accumulation under control."],["Is Highland Park within the Chattanooga service area?","Yes. Highland Park is one of our established Chattanooga neighborhoods. We run regular city routes and Highland Park is well within our coverage area."]] },
  "flintstone":       { name:"Flintstone, GA",         desc:"Flintstone is a Walker County community in the hills of North Georgia with a mix of rural homesteads and established residential neighborhoods. Scoopy Doo serves Flintstone as part of our North Georgia coverage with no extra Walker County fees.", hoods:["Flintstone proper","US-27 corridor","Walker County residential","Lookout Valley vicinity","Cloud Springs Road area"], faqs:[["Do you service Flintstone, GA?","Yes. Flintstone is within our North Georgia service coverage. We do not charge extra fees for Walker County locations. Pricing is based on yard size and number of dogs."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all tools and footwear between every single yard to prevent the spread of bacteria and parasites."],["Can you handle larger rural properties?","Yes. We service a range of property sizes including larger rural lots and use a grid-pattern approach to make sure nothing is missed."]] },
  "downtown":         { name:"Downtown Chattanooga, TN", desc:"Downtown Chattanooga is one of the most walkable dog-friendly urban environments in Tennessee. Scoopy Doo provides professional pet waste removal for downtown homes, condos with private outdoor spaces, and townhomes throughout the core and adjacent neighborhoods.", hoods:["Downtown proper","Bluff View","Southside","MLK District","North Shore","Riverfront area"], faqs:[["Do you service downtown Chattanooga homes and condos?","Yes. We service private yards, townhome outdoor spaces, and residential properties throughout downtown Chattanooga and adjacent neighborhoods including Southside, Bluff View, and the MLK District."],["Why does pet waste matter near the Tennessee River?","Storm drains in downtown Chattanooga connect directly to the Tennessee River. Dog waste washes into the water during rain, contributing bacteria and pathogens that affect water quality."],["How often should downtown properties be cleaned?","Weekly service is most popular for downtown properties. Compact yards with dogs fill up quickly and weekly pickup keeps the space pleasant year-round."]] }
};

function makeLocContent(slug) {
  var d = LOC[slug];
  if (!d) return "";
  var h = "<h1>Dog Poop Removal in " + d.name + " | Scoopy Doo Pet Waste Removal</h1>";
  h += "<p>" + d.desc + "</p>";
  h += "<h2>Neighborhoods We Serve in " + d.name + "</h2><ul>";
  d.hoods.forEach(function(n){ h += "<li>" + n + "</li>"; });
  h += "</ul>";
  h += "<h2>Frequently Asked Questions</h2>";
  d.faqs.forEach(function(f){ h += "<h3>" + f[0] + "</h3><p>" + f[1] + "</p>"; });
  h += "<p>Get a free quote at scoopychatt.com/quoterequest. We respond the same day.</p>";
  return h;
}

// FAQPage schema for /faq route
const SCHEMA = {
  '/faq': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How much does dog poop removal cost in Chattanooga?","acceptedAnswer":{"@type":"Answer","text":"Scoopy Doo pricing depends on yard size and number of dogs. Every quote is free and personalized at scoopychatt.com/quoterequest. There are no long-term contracts."}},{"@type":"Question","name":"How often does Scoopy Doo come to clean?","acceptedAnswer":{"@type":"Answer","text":"Weekly and every-other-week service is available. Weekly is the most popular option for one or two dogs. One-time cleanups are also available."}},{"@type":"Question","name":"Does Scoopy Doo serve North Georgia?","acceptedAnswer":{"@type":"Answer","text":"Yes. Scoopy Doo serves Ringgold, Rossville, Fort Oglethorpe, and Flintstone in Catoosa and Walker counties Georgia, at the same rates as Tennessee locations."}},{"@type":"Question","name":"What happens during a pet waste removal visit?","acceptedAnswer":{"@type":"Answer","text":"You receive a text when the technician is on the way. The technician cleans the entire yard, secures the gate, and sends a photo confirmation. Waste is double-bagged and hauled fully off the property."}},{"@type":"Question","name":"Is there a contract for Scoopy Doo service?","acceptedAnswer":{"@type":"Answer","text":"No contracts, ever. You can start, pause, or cancel service at any time with no cancellation fees."}},{"@type":"Question","name":"Does Scoopy Doo sanitize equipment between yards?","acceptedAnswer":{"@type":"Answer","text":"Yes. All scooping tools and footwear are sanitized between every yard to prevent the spread of bacteria and parasites."}},{"@type":"Question","name":"Does Scoopy Doo remove waste from the property?","acceptedAnswer":{"@type":"Answer","text":"Yes. Waste is double-bagged and hauled away from the property entirely. It does not go in the trash can or stay by the gate."}},{"@type":"Question","name":"How do I get started with Scoopy Doo?","acceptedAnswer":{"@type":"Answer","text":"Request a free quote at scoopychatt.com/quoterequest. Most new customers can start within 2-5 days."}}]}</script>'
,
  '/services': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Pet Waste Removal Services - Scoopy Doo LLC","description":"Weekly, twice-weekly, every-other-week, and one-time pet waste removal for homes, HOAs, and commercial properties in Chattanooga TN and North Georgia.","url":"https://www.scoopychatt.com/services","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/dog-poop-removal-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Dog poop removal","name":"Dog Poop Removal - Scoopy Doo LLC","description":"Professional dog poop removal for homes, HOAs, and commercial properties in Chattanooga TN and North Georgia. Weekly, twice-weekly, every-other-week, and one-time cleanups with on-the-way texts and gate photo confirmation.","url":"https://www.scoopychatt.com/dog-poop-removal-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/pet-waste-removal-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Pet Waste Removal - Scoopy Doo LLC","description":"Full-service pet waste removal in Chattanooga TN and North Georgia with weekly, twice-weekly, every-other-week, and one-time visits. All waste is double-bagged and hauled off the property.","url":"https://www.scoopychatt.com/pet-waste-removal-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/dog-poop-scooping-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pooper scooper service","name":"Dog Poop Scooping - Scoopy Doo LLC","description":"Reliable pooper scooper service in Chattanooga TN and North Georgia. Every visit includes a full yard sweep in a grid pattern and a gate photo confirmation when the job is done.","url":"https://www.scoopychatt.com/dog-poop-scooping-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/yard-cleanup-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Dog waste yard cleanup","name":"Dog Waste Yard Cleanup - Scoopy Doo LLC","description":"One-time and recurring dog waste yard cleanup in Chattanooga TN and North Georgia. No contracts required and free quotes online.","url":"https://www.scoopychatt.com/yard-cleanup-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/one-time-cleanup': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"One-time yard cleanup","name":"One-Time Yard Cleanup - Scoopy Doo LLC","description":"One-time deep cleanup of accumulated dog waste starting at $85 for homes in Chattanooga TN and North Georgia. No ongoing commitment required.","url":"https://www.scoopychatt.com/one-time-cleanup","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>'
};

const routes = {
  '/press': ['Scoopy Doo in the News | Press and Media Coverage | Chattanooga Pet Waste Removal', 'See news coverage of Scoopy Doo LLC, the largest pet waste removal company in the Chattanooga area. Featured in the Chattanoogan and on WDEF News 12.'],
  '/': ['Pet Waste Removal & Dog Poop Removal | Chattanooga TN | Scoopy Doo', 'Pet waste removal & dog poop pickup in Chattanooga TN & North Georgia. 5-star rated with 90+ Google reviews. Weekly service from $20 per visit. Free quotes.'],
  '/services': ['Pet Waste Removal Services in Chattanooga, TN | Scoopy Doo', 'Weekly, every-other-week & one-time dog poop removal in Chattanooga. See what Scoopy Doo offers and book today.'],
  '/near-me': ['Pooper Scooper Service Near Me in Chattanooga, TN', 'Looking for a pooper scooper service near you in Chattanooga? Scoopy Doo offers reliable local dog waste removal.'],
  '/one-time-cleanup': ['One-Time Dog Poop Cleanup in Chattanooga, TN | Scoopy Doo', 'Get a one-time dog poop cleanup in Chattanooga, TN. Perfect for spring cleaning or first-time service.'],
  "/cost-calculator": ["Dog Poop Cost Calculator | Chattanooga TN | Scoopy Doo", "Estimate weekly, twice-weekly, and one-time pooper scooper pricing in Chattanooga and North Georgia, then get a free exact quote from Scoopy Doo."],
  '/how-it-works': ['How It Works | Scoopy Doo Pet Waste Removal Chattanooga', 'Easy online quotes, secure online payment, on-the-way texts, and gate photo proof after every visit. Working with Scoopy Doo is simple.'],
  '/doggy-doors': ['Professional Dog Door Installation in Chattanooga, TN | Scoopy Doo Doggy Doors', 'Scoopy Doo Doggy Doors installs professional dog doors in Chattanooga and North Georgia homes. Good, Better, and Best options, professionally installed.'],
  '/dog-poop-removal-chattanooga': ['Dog Poop Removal in Chattanooga, TN | Scoopy Doo LLC', 'Professional dog poop removal in Chattanooga, TN. Dependable weekly service, fully insured.'],
  '/pet-waste-removal-chattanooga': ['Pet Waste Removal in Chattanooga, TN | Scoopy Doo', 'Expert pet waste removal in Chattanooga, TN for homes, HOAs & businesses. Request a free quote.'],
  '/dog-poop-scooping-chattanooga': ['Dog Poop Scooping Service in Chattanooga, TN | Scoopy Doo', 'Reliable dog poop scooping in Chattanooga, TN. Weekly and every-other-week pooper scooper service.'],
  '/yard-cleanup-chattanooga': ['Yard Cleanup for Pet Owners in Chattanooga, TN | Scoopy Doo', 'Complete yard cleanup for pet owners in Chattanooga, TN. Book a one-time or recurring cleanup.'],
  '/service-areas': ['Service Areas | Pet Waste Removal Around Chattanooga, TN', 'Scoopy Doo serves Chattanooga and surrounding areas. See the neighborhoods we cover.'],
  '/about': ['About Scoopy Doo | Chattanooga Pet Waste Removal', "Meet Scoopy Doo LLC, Chattanooga's locally owned pet waste removal company."],
  '/faq': ['Pet Waste Removal FAQs | Scoopy Doo Chattanooga', 'Answers to common questions about dog poop removal in Chattanooga: pricing, scheduling, and more.'],
  '/quote': ['Get a Free Pet Waste Removal Quote | Chattanooga, TN', 'Get a fast, free quote for dog poop removal in Chattanooga, TN.'],
  '/spring-special': ['Spring Special: Buy 2 Months, Get 1 Free | Scoopy Doo', 'Limited-time Chattanooga spring special from Scoopy Doo.'],
  '/pet-safe-checklist': ['Pet-Safe Yard Checklist | Scoopy Doo Chattanooga', 'A free pet-safe yard checklist for Chattanooga dog owners.'],
  '/dog-park-guide': ['Chattanooga Dog Park Guide for Dog Owners | Scoopy Doo', "Discover Chattanooga's best dog parks. A local guide from Scoopy Doo."],
  '/blog': ['Pet Waste & Dog Care Blog | Scoopy Doo Chattanooga', 'Tips on pet waste removal, yard health, and dog care for Chattanooga homeowners.'],
  '/privacy-policy': ['Privacy Policy | Scoopy Doo LLC', 'Privacy policy for Scoopy Doo LLC.'],
  '/terms-of-service': ['Terms of Service | Scoopy Doo LLC', 'Terms of service for Scoopy Doo LLC pet waste removal.'],
  '/blog/professional-waste-removal-benefits': ['Benefits of Professional Pet Waste Removal | Scoopy Doo Chattanooga', 'Why professional dog waste removal is safer and more thorough than DIY. Scoopy Doo serves Chattanooga and surrounding areas weekly.'],
  '/blog/winter-dog-poop-cleanup-chattanooga': ['Winter Dog Poop Cleanup in Chattanooga | Scoopy Doo', 'Cold weather does not stop dog waste from piling up. Learn why Chattanooga yards need winter pet waste removal and what Scoopy Doo service costs from 18 dollars a visit.'],
  '/blog/seasonal-pet-care-tips': ['Seasonal Pet Care Tips for Chattanooga Dog Owners | Scoopy Doo', 'Keep your yard clean and safe year-round with seasonal pet waste tips from Scoopy Doo LLC in Chattanooga, TN.'],
  '/blog/health-benefits-yard-cleanup': ['Health Benefits of Regular Yard Cleanup for Pet Owners | Scoopy Doo', 'Regular dog waste removal protects your family from bacteria and parasites. Learn why weekly cleanup matters for Chattanooga homeowners.'],
  '/blog/customer-success-stories': ['Customer Success Stories | Scoopy Doo Pet Waste Removal Chattanooga', 'Real stories from Chattanooga homeowners and HOAs who rely on Scoopy Doo for weekly pet waste removal.'],
  '/blog/diy-vs-professional': ['DIY vs Professional Dog Waste Removal | Scoopy Doo Chattanooga', 'Compare DIY pet waste cleanup to professional pooper scooper service in Chattanooga, TN. See which option saves time and money.'],
  '/blog/lawn-health-and-pet-waste': ['How Pet Waste Affects Your Lawn Health | Scoopy Doo Chattanooga', 'Dog waste kills grass and harms soil. Learn how regular professional cleanup protects your Chattanooga lawn from long-term damage.'],
  '/blog/health-risks-of-pet-waste': ['Health Risks of Unmanaged Pet Waste | Scoopy Doo Chattanooga', 'Dog waste carries bacteria, hookworms, roundworms, and giardia. Learn the health risks and how Scoopy Doo protects Chattanooga families.'],
  '/blog/pet-waste-management-guide': ['The Complete Pet Waste Management Guide for Dog Owners | Scoopy Doo', 'Everything Chattanooga dog owners need about pet waste management - frequency, disposal, health risks, and professional service options.'],
  '/blog/how-often-scoop-dog-poop-chattanooga': ['How Often Should You Scoop Dog Poop in Chattanooga? | Scoopy Doo', 'Weekly scooping is the gold standard. Learn why cleanup frequency matters for lawn health and family safety in Chattanooga, TN.'],
  '/blog/spring-pet-care-checklist': ['Spring Pet Care Checklist for Chattanooga Dog Owners | Scoopy Doo', 'Spring in Chattanooga means wet yards hiding months of pet waste. Use this checklist to get your yard cleaned up and ready.'],
  '/blog/is-dog-waste-bad-for-lawn': ['Is Dog Waste Bad for Your Lawn? | Scoopy Doo Chattanooga', 'Yes - dog waste kills grass and damages soil. Learn what it does to your Chattanooga yard and how professional cleanup helps.'],
  '/blog/best-pooper-scooper-services-chattanooga': ['Best Pooper Scooper Services in Chattanooga, TN | Scoopy Doo', 'Looking for the best dog poop removal in Chattanooga? Online quotes, on-the-way texts, gate photo confirmation. No contracts.'],
  '/blog/is-dog-poop-hurting-your-chattanooga-yard': ['Is Dog Poop Hurting Your Chattanooga Yard? | Scoopy Doo', 'Dog waste damages grass and soil over time. Find out if your Chattanooga yard is being harmed and how Scoopy Doo can help.'],
  '/blog/chattanooga-pet-waste-removal-homeowners': ['Pet Waste Removal Guide for Chattanooga Homeowners | Scoopy Doo', 'A complete guide for Chattanooga homeowners on pet waste management - health risks, lawn damage, waterway protection, and professional service.'],
  '/blog/commercial-pet-waste-removal-chattanooga': ['Commercial Pet Waste Removal in Chattanooga, TN | Scoopy Doo', 'Professional pet waste removal for apartments, HOAs, and businesses in Chattanooga. Flexible scheduling, no contracts.'],
  '/blog/fall-yard-care-checklist-chattanooga': ['Fall Yard Care Checklist for Chattanooga Dog Owners | Scoopy Doo', 'A fall pet waste and yard care checklist for Chattanooga dog owners. Learn why leaf season makes cleanup harder and how professional dog poop removal helps.'],
  '/blog/how-often-clean-yard': ['How Often Should You Clean Your Yard of Dog Waste? | Scoopy Doo', 'Weekly is the gold standard. Learn the right cleanup frequency based on your dog count, yard size, and Chattanooga season.'],
  '/blog/podcast-blog': ['Scoopy Doo on the Podcast | The Chattanooga Pet Waste Removal Story', 'Hear the Scoopy Doo LLC founder discuss starting a pet waste removal business in Chattanooga, TN.'],
  '/blog/signal-mountain': ['Pet Waste Removal Tips for Signal Mountain, TN | Scoopy Doo Blog', 'Scoopy Doo serves Signal Mountain with thorough yard cleanup. We handle larger lots and wooded terrain every week.'],
  '/blog/dog-poop-cleanup-chattanooga-summer-heat': ['Dog Poop Cleanup in Chattanooga During Hot, Humid Weather | Scoopy Doo', 'Summer heat and humidity make dog waste more dangerous. Learn why Chattanooga yards need regular cleanup during the hot months and how Scoopy Doo can help.'],
  '/blog/dog-poop-laws-chattanooga': ['Is It Illegal to Not Pick Up Dog Poop in Chattanooga? | Scoopy Doo', 'Yes, Chattanooga law requires dog owners to pick up after their pets. Here is what City Code Chapter 7 says, the fines you could face, and how to stay compliant.'],
  '/blog/soddy-daisy': ['Pet Waste Removal in Soddy-Daisy, TN | Scoopy Doo Blog', 'Scoopy Doo serves Soddy-Daisy and Chickamauga Lake area homeowners. Waterfront cleanup protects the lake and your family.'],
  '/blog/one-time-dog-poop-cleanup-chattanooga': ['One-Time Dog Poop Cleanup in Chattanooga: Cost & How It Works | Scoopy Doo', 'What a one-time dog poop cleanup costs in Chattanooga, when to book one, and how it works. One-time yard cleanups from $85 with no contract. Call 423-600-5040.'],
  '/blog/hoa-pet-waste-removal-chattanooga': ['HOA Pet Waste Removal in Chattanooga: A Board Guide | Scoopy Doo', 'How HOA and community pet waste removal works in Chattanooga: what is included, how pricing is quoted, and how to set up service for common areas and dog stations. Call 423-600-5040.'],
  '/blog/new-puppy-pet-waste-removal-chattanooga': ['New Puppy Owner Guide: Pet Waste Cleanup in Chattanooga | Scoopy Doo', 'Bringing home a new puppy in Chattanooga? Here is how to set up a pet waste cleanup routine, why it matters for house training and health, and what professional service costs.'],
  '/blog/dog-poop-removal-north-georgia': ["Dog Poop Removal in Ringgold, Fort Oglethorpe and North Georgia | Scoopy Doo", "Scoopy Doo provides dog poop removal in Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA. Weekly service from $20 per visit, no contracts required."],
'/blog/yard-cleanup-before-selling-home-chattanooga': ["Do You Need to Clean Up Dog Waste Before Selling Your Chattanooga Home? | Scoopy Doo", "Selling a home in Chattanooga? Here is why yard cleanup and pet waste removal matter before listing photos and showings, plus a pre-listing checklist and pricing."],
};

const gaLocations = new Set(['ringgold','rossville','flintstone','fort-oglethorpe']);
const locationPages = [
  'chattanooga','hixson','red-bank','signal-mountain','ooltewah','east-brainerd',
  'soddy-daisy','cleveland','apison','collegedale','highland-park','downtown',
  'east-ridge','lookout-mountain',
  'ringgold','rossville','flintstone','fort-oglethorpe'
];
locationPages.forEach(function(loc) {
  var city = loc.split('-').map(function(w){return w[0].toUpperCase()+w.slice(1);}).join(' ');
  var state = gaLocations.has(loc) ? 'GA' : 'TN';
  routes['/service/' + loc] = [
    'Dog Poop Removal ' + city + ' ' + state + ' | Scoopy Doo',
    'Professional pet waste removal in ' + city + ', ' + state + '. Weekly & every-other-week pooper scooper service. Get your free quote today.'
  ];
});

// Per-route social share image. Routes not listed here keep the site default
// og:image from index.html. Crawlers read this static HTML, not the React app,
// so a route needs an entry here for its link preview to differ.
const IMAGES = {
  '/doggy-doors': { url: 'https://www.scoopychatt.com/images/doggy-doors-hero.png', w: 1376, h: 768, alt: 'Dog using a professionally installed Scoopy Doo Doggy Door with app-controlled smart collar access.' }
};

function injectMeta(html, title, desc, canonical, staticHtml, schemaHtml, image) {
  var result = html
    .replace(/<title>[^<]*<\/title>/, '<title>' + title + '<\/title>')
    .replace(/(<meta name="description" content=")[^"]*(")/,'$1' + desc + '$2')
    .replace(/(<link rel="canonical" href=")[^"]*(")/,'$1' + canonical + '$2')
    .replace(/(<meta property="og:title" content=")[^"]*(")/,'$1' + title + '$2')
    .replace(/(<meta property="og:description" content=")[^"]*(")/,'$1' + desc + '$2')
    .replace(/(<meta property="og:url" content=")[^"]*(")/,'$1' + canonical + '$2')
    .replace(/(<meta name="twitter:title" content=")[^"]*(")/,'$1' + title + '$2')
    .replace(/(<meta name="twitter:description" content=")[^"]*(")/,'$1' + desc + '$2');
  if (image) {
    result = result
      .replace(/(<meta property="og:image" content=")[^"]*(")/,'$1' + image.url + '$2')
      .replace(/(<meta property="og:image:width" content=")[^"]*(")/,'$1' + image.w + '$2')
      .replace(/(<meta property="og:image:height" content=")[^"]*(")/,'$1' + image.h + '$2')
      .replace(/(<meta property="og:image:alt" content=")[^"]*(")/,'$1' + image.alt + '$2')
      .replace(/(<meta name="twitter:image" content=")[^"]*(")/,'$1' + image.url + '$2');
  }
  if (staticHtml) {
    result = result.replace(BODY_CLOSE, '<div id="scoopy-content" style="display:none" aria-hidden="true">' + staticHtml + DIV_CLOSE + BODY_CLOSE);
  }
  if (schemaHtml) {
    result = result.replace('</head>', schemaHtml + '</head>');
  }
  return result;
}

var count = 0;

// --- GEO schema injection (added) ---
var FAQ_PAIRS = [
  ["How do I schedule pet waste removal service?","Request a free quote at scoopychatt.com/quote with your yard details and number of dogs. We respond the same day and most new customers start within 2 to 5 days."],
  ["Does Scoopy Doo serve North Georgia?","Yes. We serve Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA along with Chattanooga and surrounding Tennessee areas, with no extra charge for North Georgia service."],
  ["Is there a contract or long-term commitment?","No. Scoopy Doo never requires a contract. You can pause, reschedule, or cancel anytime with no cancellation fees."],
  ["How much does dog poop removal cost in Chattanooga?","Pricing depends on how many dogs you have and how often we visit. We offer weekly, twice-weekly, every-other-week, one-time, commercial, and HOA options. Use the cost calculator at scoopychatt.com/cost-calculator or request a free quote for exact pricing."],
  ["How often should I have my yard cleaned?","Weekly service is the most popular and keeps your yard consistently clean and safe. Homes with multiple dogs or heavy use often choose twice-weekly, while every-other-week works for lighter needs."],
  ["What happens on each visit?","You get an on-the-way text before we arrive, a full grid-pattern sweep of your entire yard, double-bagged waste hauled completely off your property, and a gate photo confirmation when we finish."],
  ["Do you offer one-time cleanups?","Yes. One-time yard cleanups are great for spring cleaning, move-outs, or before an event, and a good way to start fresh before beginning recurring service."],
  ["Do you handle commercial and HOA properties?","Yes. Scoopy Doo provides pet waste removal for apartments, HOAs, dog parks, and shared common areas with flexible scheduling and no contracts."]
];
function ldScript(obj){return '<script type="application/ld+json">'+JSON.stringify(obj)+'</'+'script>';}
function faqSchema(pairs){var items=[];for(var i=0;i<pairs.length;i++){items.push({"@type":"Question","name":pairs[i][0],"acceptedAnswer":{"@type":"Answer","text":pairs[i][1]}});}return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":items};}
function titleCaseSlug(slug){return slug.split("-").map(function(w){return w.charAt(0).toUpperCase()+w.slice(1);}).join(" ");}
var HOME_FAQ_PAIRS=[["What is Scoopy Doo and what does the service include?","Scoopy Doo LLC is Chattanooga's locally owned dog poop removal and pooper scooper service. Every visit includes a full grid-pattern yard sweep, double-bagged waste removal hauled off your property, gate closure, and a photo confirmation sent to you. No contracts - cancel or change anytime."],["How does Scoopy Doo pet waste removal work?","It's simple: request a free quote online, we send you pricing based on yard size and number of dogs, and you pick a schedule. We show up on your day, text you when we're on the way, clean the entire yard, close your gate, and send a photo when done. Payment is handled online - no checks, no phone tag."],["Do you offer a scoopy poopy service near Chattanooga, TN?","Yes - Scoopy Doo provides professional pooper scooper and scoopy poopy service throughout the Chattanooga metro including Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Lookout Mountain, Soddy-Daisy, and North Georgia communities like Ringgold, Rossville, and Fort Oglethorpe."],["How often should I schedule dog waste removal?","Weekly service is our most popular option and works well for most one- or two-dog households. We also offer 2x weekly service for high-traffic yards and multiple dogs, every-other-week for lower-use yards, and one-time cleanups if you need to start fresh before beginning a regular schedule."],["Is Scoopy Doo dog waste removal safe for kids and pets?","Yes. We sanitize all scooping equipment between every yard to prevent cross-contamination. We never use harmful chemicals in your yard, and we haul all waste fully off the property. A clean yard is a safer yard - dog waste carries bacteria and parasites that are hazardous to children and other animals."],["How much does pooper scooper service cost in Chattanooga?","Pricing is based on yard size and the number of dogs. Most Chattanooga homeowners pay between $18 and $36 per visit. The fastest way to get your exact price is to submit a free quote request - we respond the same day, usually within a few hours."],["Do you service HOAs and apartment communities?","Yes. We service HOA common areas, dog-walking paths, and pet waste stations in addition to individual residential homes. We can invoice HOA boards directly and maintain visit records for compliance documentation."]];
function routeSchema(route){
  var base="https://www.scoopychatt.com";
  if(route==="/"){return ldScript({"@context":"https://schema.org","@type":"LocalBusiness","@id":"https://www.scoopychatt.com/#business","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+1-423-600-5040","email":"info@scoopychatt.com","image":"https://horizons-cdn.hostinger.com/d0188638-a120-4cbd-8c61-d1420711a271/8088ef4935a7739f1747caefac1fdcc6.jpg","priceRange":"$","address":{"@type":"PostalAddress","streetAddress":"100 Market Street","addressLocality":"Chattanooga","addressRegion":"TN","postalCode":"37402","addressCountry":"US"},"geo":{"@type":"GeoCoordinates","latitude":"35.0456","longitude":"-85.3097"},"areaServed":["Chattanooga TN","Hixson TN","Red Bank TN","Signal Mountain TN","Ooltewah TN","East Brainerd TN","Soddy-Daisy TN","Cleveland TN","East Ridge TN","Lookout Mountain TN","Collegedale TN","Apison TN","Highland Park Chattanooga TN","Downtown Chattanooga TN","Ringgold GA","Rossville GA","Flintstone GA","Fort Oglethorpe GA"],"openingHoursSpecification":[{"@type":"OpeningHoursSpecification","dayOfWeek":["Monday","Tuesday","Wednesday","Thursday","Friday"],"opens":"08:00","closes":"18:00"}],"aggregateRating":{"@type":"AggregateRating","ratingValue":"5.0","reviewCount":"90"},"sameAs":["https://www.facebook.com/profile.php?id=61578292444117","https://www.instagram.com/scoopychatt","https://www.yelp.com/biz/scoopy-doo-chattanooga","https://www.bbb.org/us/ga/ringgold/profile/pet-waste-removal/scoopy-doo-llc-0483-80013696","https://share.google/qZ8AFwG3qiRu6lvwi","https://www.petworks.com/listing/scoopy-doo-professional-dog-waste-removal-service-chattanooga-tn","https://nextdoor.com/page/scoopy-doo-llc-ringgold-ga","https://www.pooppages.com/directory/georgia/ringgold/scoopy-doo-c37smt"]})+ldScript(faqSchema(HOME_FAQ_PAIRS));}if(route==="/press"){var col={"@context":"https://schema.org","@type":"CollectionPage","name":"Scoopy Doo in the News","url":base+"/press","description":"News coverage and press mentions of Scoopy Doo LLC, the largest pet waste removal company in the Chattanooga TN area.","about":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","url":base,"telephone":"+1-423-600-5040"}};var art={"@context":"https://schema.org","@type":"NewsArticle","headline":"14-Year-Old Entrepreneur Builds Chattanooga Largest Pet Waste Removal Company In Under A Year","url":"https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx","datePublished":"2026-06-23","image":"https://images.chattanoogan.com/2026/6/article.520251.jpg","publisher":{"@type":"Organization","name":"Chattanoogan.com","url":"https://www.chattanoogan.com"},"about":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","url":base},"mainEntityOfPage":"https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx"};return ldScript(col)+ldScript(art);}if(route==="/faq"){return ldScript(faqSchema(FAQ_PAIRS));}
  if(route.indexOf("/service/")===0){
    var slug=route.slice(9);
    var d=(typeof LOC!=="undefined")?LOC[slug]:null;
    if(!d){return "";}
    var city=titleCaseSlug(slug);
    var svc={"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Dog Poop Removal in "+city,"description":d.desc,"url":base+route,"areaServed":{"@type":"City","name":city},"provider":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","telephone":"+1-423-600-5040","url":base,"priceRange":"$$"}};
    var out=ldScript(svc);
    if(d.faqs&&d.faqs.length){out+=ldScript(faqSchema(d.faqs));}
    return out;
  }
  return "";
}
// --- end GEO schema injection ---

for (var route in routes) {
  var parts = routes[route];
  var title = parts[0];
  var desc = parts[1];
  var canonical = BASE + route;
  var locSlug = route.startsWith('/service/') ? route.replace('/service/', '') : null;
  var staticHtml = SC[route] || (locSlug ? makeLocContent(locSlug) : '');
  var schemaHtml = SCHEMA[route] || '';
  var html = injectMeta(template, title, desc, canonical, staticHtml, schemaHtml, IMAGES[route]);
  var dirPath = path.join(distDir, route);
  fs.mkdirSync(dirPath, { recursive: true });
  var __s = routeSchema(route); if (__s) { html = html.replace("</head>", __s + "</head>"); }
      fs.writeFileSync(path.join(dirPath, 'index.html'), html);
  count++;
}
console.log('SEO inject complete: ' + count + ' pages.');
} catch(e) {
  console.error('SEO inject warning:', e.message);
  process.exit(0);
}
