#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

try {
const BASE = 'https://www.scoopychatt.com';
const distDir = path.join(process.cwd(), 'dist', 'apps', 'web');
const templatePath = path.join(distDir, 'index.html');

if (!fs.existsSync(templatePath)) {
  console.log('SEO inject: dist/apps/web/index.html not found, skipping (build cache active)');
  process.exit(0);
}

const template = fs.readFileSync(templatePath, 'utf-8');

const BODY_CLOSE = '<' + '/body>';
const DIV_CLOSE = '<' + '/div>';

// Static content blocks for key non-location pages
const SC = {
  '/press': "<h1>Scoopy Doo in the News: Chattanooga's Largest Pet Waste Removal Company</h1><p>Scoopy Doo LLC is the largest and fastest-growing pet waste removal company in the Chattanooga, TN area, serving more than 150 clients with 90 five-star reviews across Chattanooga and North Georgia. In June 2026, Scoopy Doo was featured by the Chattanoogan, and in July 2026 by WDEF News 12.</p><h2>Featured in the Chattanoogan</h2><p>14-Year-Old Entrepreneur Builds Chattanooga's Largest Pet Waste Removal Company In Under A Year. Founder Leighton Carter grew Scoopy Doo LLC from a single customer to more than 150 active clients in under a year, with her dad Brandon supporting her along the way, serving dog owners, HOAs, apartment communities, and commercial properties across Chattanooga and North Georgia. <a href='https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx'>Read the full article on Chattanoogan.com</a>.</p><h2>Featured on WDEF News 12</h2><p>On July 2, 2026, WDEF News 12 featured Scoopy Doo LLC, the father and daughter pet waste removal company. Fourteen-year-old Leighton Carter started the company with help from her dad, Brandon, and the family now runs Scoopy Doo full-time, serving more than 150 customers across the Chattanooga area with a team of three. Scoopy Doo offers weekly, bi-weekly, and twice-a-week yard cleanings. <a href='https://www.wdef.com/scoopy-doo-llc-pet-waste-removal/'>Watch the story on WDEF.com</a>.</p><h2>Press and Media Inquiries</h2><p>For press and media inquiries, contact Scoopy Doo at info@scoopychatt.com.</p>",
  '/services': "<h1>Pet Waste Removal Services in Chattanooga, TN</h1><p>Scoopy Doo offers professional pet waste removal for homes, businesses, and HOAs in Chattanooga TN and North Georgia. All services include on-the-way texts and gate photo confirmation. No contracts required.</p><h2>Weekly Dog Poop Removal</h2><p>Most popular service. A technician visits once per week, removes all dog waste, texts on the way, and sends a gate photo after each visit. Pricing based on yard size and number of dogs. Free quote at scoopychatt.com/quote.</p><h2>Every-Other-Week Pooper Scooper Service</h2><p>Every two weeks. Ideal for smaller yards or fewer dogs.</p><h2>One-Time Yard Cleanup</h2><p>Single deep-clean visit. Perfect for spring cleanup, before a party, or as a first visit.</p><h2>Commercial Pet Waste Removal</h2><p>Regular scheduled service for apartment complexes, dog parks, and businesses in Chattanooga and North Georgia.</p><h2>HOA Common Area Cleanup</h2><p>Scheduled pet waste removal for shared green spaces and common areas throughout the Chattanooga metro area.</p><h2>What do extra dogs cost, and how does billing work?</h2><p>The base rates include your first dog. Weekly service adds $2 per visit for each additional dog, twice-weekly adds $1, and every-other-week adds $3, so weekly for two dogs is $22 per visit. Scoopy Doo prices per visit and bills once a month, with a card kept securely on file and a receipt by email. There are no contracts.</p><h2>Does the waste leave my property?</h2><p>All waste is double-bagged and placed in your outdoor bin as standard, never left at the gate. Waste takeaway, where the bags leave the property with us instead, is $5 per visit. Haul-away is already included on one-time cleanups at no extra charge.</p><h2>Do you offer yard deodorizing, and what does it cost?</h2><p>Yes. Deodorizing and sanitizing is $20 per visit and can be added to any recurring plan or to a one-time cleanup. It neutralizes the odor compounds and bacteria left in the soil after the waste itself is removed, rather than masking them, and is most worthwhile for heavily used yards, areas near a patio, and yards being prepared for an event or a home sale. For most yards, removing all the waste and watering the affected areas heavily clears the smell without a treatment. Full guide at scoopychatt.com/blog/how-to-get-rid-of-dog-poop-smell-in-yard-chattanooga.</p><h2>Weekly or every other week: which do I need?</h2><p>Weekly service is $20 per visit for the first dog and every-other-week service is $33 per visit, which works out to $1,040 versus $858 a year, about $15 a month apart for twice the visits. Weekly is the better fit for two or more dogs, small fenced yards, and the humid Chattanooga months from May through September. Every-other-week suits one dog on a quarter acre or more. You can switch between them any time because there is no contract. Full comparison at scoopychatt.com/blog/weekly-vs-biweekly-dog-poop-service-chattanooga.</p>",
  '/faq': "<h1>Frequently Asked Questions About Dog Poop Removal in Chattanooga</h1><h2>How much does dog poop removal cost in Chattanooga?</h2><p>Scoopy Doo weekly service starts at $20 per visit for one dog. Twice-weekly service is $18 per visit and every-other-week service starts at $33 per visit. One-time yard cleanups start at $85, covering up to three dogs, with each additional dog adding $15 and haul-away included. All pricing is based on yard size and number of dogs -- every quote is free and personalized at scoopychatt.com/quoterequest. There are no contracts.</p><h2>Does Scoopy Doo serve North Georgia?</h2><p>Yes. Scoopy Doo serves Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA in addition to Chattanooga, Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, East Ridge, and Lookout Mountain TN. North Georgia customers pay the same rates as Tennessee locations.</p><h2>What happens on each visit?</h2><p>You receive a text when your technician is on the way. The technician searches the entire yard in a grid pattern. All waste is double-bagged and placed in your outdoor bin, or hauled off the property for $5 per visit. After every visit you receive a gate photo confirmation so you know the yard is clean and the gate is secured.</p><h2>Is there a contract?</h2><p>No contracts, ever. You can start, pause, or cancel service at any time. There are no cancellation fees or minimum commitments.</p><h2>How often should I have my yard cleaned?</h2><p>Weekly is the gold standard for homes with one or two dogs and prevents waste from building up and damaging grass. Every-other-week works well for smaller yards or single-dog households. One-time cleanups are ideal for spring cleaning, before a party, or before listing a home for sale.</p><h2>Do I need to be home during service?</h2><p>No. Most Scoopy Doo customers are not home during service. Just make sure gate access is available. You will receive an on-the-way text and a gate photo confirming the visit is complete.</p><h2>How quickly can service start?</h2><p>Most new customers start within 2 to 5 days of requesting a quote. Request a free quote at scoopychatt.com/quoterequest and Scoopy Doo responds the same day.</p><h2>Do you charge extra for multiple dogs?</h2><p>Yes, there is a small additional fee per extra dog to account for the additional waste and time. Your free quote will include the exact price for your yard size and dog count.</p><h2>Are you insured?</h2><p>Yes. Scoopy Doo is fully insured on every visit.</p><h2>What is a one-time cleanup?</h2><p>A one-time deep-clean visit removes all accumulated waste. It is ideal for spring cleaning, before a party, before listing a home, or as a first visit before starting regular service. One-time cleanups start at $85 and can be booked at scoopychatt.com/one-time-cleanup.</p>",
  '/service-areas': "<h1>Pet Waste Removal Service Areas - Chattanooga TN and North Georgia</h1><p>Scoopy Doo serves Chattanooga, TN and the surrounding metro area including North Georgia communities. We run regular routes throughout the region and most new customers can start within 2-5 days of a free quote.</p><h2>Tennessee Service Areas</h2><ul><li>Chattanooga, TN</li><li>Hixson, TN</li><li>Red Bank, TN</li><li>Signal Mountain, TN</li><li>Lookout Mountain, TN</li><li>Soddy-Daisy, TN</li><li>Ooltewah, TN</li><li>East Brainerd, TN</li><li>East Ridge, TN</li><li>Collegedale, TN</li><li>Apison, TN</li><li>Highland Park (Chattanooga), TN</li><li>Downtown Chattanooga, TN</li></ul><h2>North Georgia Service Areas</h2><ul><li>Ringgold, GA</li><li>Rossville, GA</li><li>Fort Oglethorpe, GA</li><li>Flintstone, GA</li></ul><p>All North Georgia locations are served at the same rates as Tennessee. No extra fees for crossing the state line.</p>",
  '/how-it-works': "<h1>How Scoopy Doo Pet Waste Removal Works</h1><p>Scoopy Doo makes professional dog poop removal simple. Request a free quote, we respond the same day, and most new customers start within 2-5 days.</p><h2>Step 1: Get a Free Quote</h2><p>Request a quote at scoopychatt.com/quoterequest. Tell us your yard size, number of dogs, and preferred service frequency. We respond the same day with exact pricing.</p><h2>Step 2: We Come to You</h2><p>On your scheduled day, you receive a text when your technician is on the way. No need to be home. Just make sure we have gate access.</p><h2>Step 3: Complete Yard Cleanup</h2><p>The technician searches the entire yard using a grid-pattern approach to make sure nothing is missed. All waste is double-bagged and placed in your outdoor bin, or hauled off the property for $5 per visit.</p><h2>Step 4: Gate Photo Confirmation</h2><p>After every visit, your gate is secured and a photo is sent to confirm the job is done. You know your yard is clean without having to check yourself.</p>",
  '/about': "<h1>About Scoopy Doo Pet Waste Removal - Chattanooga, TN</h1><p>Scoopy Doo LLC is a locally owned pet waste removal company serving Chattanooga, TN and North Georgia. We are a father-daughter team committed to reliable, professional service with real accountability - on-the-way texts, gate photo confirmation, and every bit of waste double-bagged into your bin or hauled off the property for $5 a visit.</p><p>Scoopy Doo LLC was founded by Leighton Carter, who started the business at 14 years old with a single customer and grew it into Chattanooga's largest pet waste removal company in under a year, with her dad Brandon supporting her every step of the way. Their story has been featured by the Chattanoogan and WDEF News 12.</p><p>We serve residential homes, HOA communities, apartment complexes, and commercial properties throughout the Chattanooga metro area including North Georgia communities in Catoosa and Walker counties. No contracts, ever.</p><p>Scoopy Doo LLC is accredited by the Better Business Bureau (BBB). See the Scoopy Doo BBB Business Review at bbb.org.</p><p>Scoopy Doo LLC is a member of aPaws, the Association of Professional Animal Waste Specialists, the national trade association for the professional pet waste removal industry, founded in 2002. The Scoopy Doo member listing is published in the aPaws member directory at apaws.org.</p>",
  '/near-me': "<h1>Pooper Scooper Service Near Me - Chattanooga TN and North Georgia</h1><p>Scoopy Doo is the locally owned pooper scooper service serving Chattanooga, TN and surrounding areas including North Georgia. We run regular routes throughout the region and offer weekly, every-other-week, and one-time dog waste removal with no contracts required.</p><p>Service areas include Chattanooga, Hixson, Red Bank, Signal Mountain, Lookout Mountain, Soddy-Daisy, Ooltewah, East Brainerd, East Ridge, Collegedale, Apison TN, Ringgold GA, Rossville GA, Fort Oglethorpe GA, and Flintstone GA. Request a free quote at scoopychatt.com/quoterequest.</p>",
  '/one-time-cleanup': "<h1>One-Time Dog Poop Cleanup in Chattanooga, TN</h1><p>Scoopy Doo offers one-time yard cleanup visits for Chattanooga and North Georgia homeowners. Perfect for spring cleaning, before a party, after a long winter, or as a first visit before starting recurring service.</p><p>The one-time cleanup includes a complete grid-pattern search of your entire yard, double-bagged waste hauled fully off the property at no extra charge, and a gate photo confirmation when done. Request your one-time cleanup at scoopychatt.com/one-time-cleanup.</p><h2>What does a one-time cleanup cost, and how many dogs does it cover?</h2><p>One-time yard cleanups start at $85, and that base covers up to three dogs. Each dog beyond three adds $15. Haul-away is included at no extra charge, unlike recurring plans where waste takeaway is $5 per visit. The final price also depends on how long the yard has gone and how large the area is.</p><h2>Can I add deodorizing to a one-time cleanup?</h2><p>Yes. Deodorizing and sanitizing is $20 per visit and can be added to a one-time cleanup or to any recurring plan. It neutralizes the odor compounds and bacteria left in the soil after the waste is removed, which is worth doing for a yard with years of buildup or one being prepared for an event or a home sale.</p><h2>How far ahead of a party should I book a one-time cleanup?</h2><p>One to two days before the event is ideal. That is close enough that a dog cannot undo the work and far enough that the grass dries and any lingering smell fades. Mow first, have the cleanup done the day before, then water the heavily used areas. Booking a week ahead is wasted money if you have dogs, and booking the morning of leaves no margin if the weather turns. Scoopy Doo books one-time cleanups seven days a week across Chattanooga and North Georgia, and most new customers are on the schedule within two to five days. Full guide at scoopychatt.com/blog/yard-cleanup-before-a-party-chattanooga.</p>",
  '/cost-calculator': "<h1>Dog Poop Removal Cost Calculator for Chattanooga, TN</h1><p>Use the free Scoopy Doo cost calculator to estimate pooper scooper service pricing in Chattanooga and North Georgia. Weekly service is $20 per visit for the first dog, twice-weekly is $18, and every-other-week is $33. Each additional dog adds $2 per visit on weekly, $1 on twice-weekly, and $3 on every-other-week. Optional waste takeaway is $5 per visit and yard deodorizing is $20 per visit. One-time yard cleanups start at $85, cover up to three dogs, include haul-away, and add $15 per dog beyond three. Pricing is per visit and billing is monthly.</p><p>Estimate your price by number of dogs and service frequency, then request a free exact quote with no contracts and no cancellation fees at scoopychatt.com/cost-calculator.</p>",
  '/comparison': "<h1>Pet Waste Removal Services in Chattanooga, TN: 2026 Comparison</h1><p>Several pet waste removal providers serve the Chattanooga TN and North Georgia area. The table below compares them by service area, frequency options, published pricing, and notable features. Where pricing is not published on the provider website, the cell is marked Not listed.</p><h2>Chattanooga Pet Waste Removal Comparison</h2><table><thead><tr><th>Service</th><th>Service Area</th><th>Frequency Options</th><th>Starting Price</th><th>Notable</th></tr></thead><tbody><tr><td>Scoopy Doo</td><td>Chattanooga TN + Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, East Ridge, Lookout Mountain + Ringgold, Rossville, Fort Oglethorpe, Flintstone GA</td><td>Weekly, every-other-week, twice-weekly, one-time</td><td>Weekly from $20/visit (1 dog)</td><td>7-day availability; on-the-way texts every visit; gate photo after every visit; optional waste takeaway at $5/visit; no contracts; locally owned; 90 Google reviews</td></tr><tr><td>ChattaPoo</td><td>Chattanooga TN + Signal Mountain</td><td>Weekly, every-other-week, one-time</td><td>Weekly from $20/visit (1 dog)</td><td>Also offers dog walking, boarding, and vet transport; Mon-Fri 7am-8pm, Sat-Sun 8am-7pm; 1 Google review</td></tr><tr><td>PooTagic</td><td>Chattanooga TN + suburbs + Ringgold, Rossville, Fort Oglethorpe GA</td><td>Not listed</td><td>Quote required</td><td>Deodorizing and sanitizing service available; 20% neighbor discount; 49 Google reviews</td></tr><tr><td>Doo Doo Blues</td><td>Chattanooga area</td><td>Not listed</td><td>Not listed</td><td>Grid-pattern scooping; deodorizing available; national franchise</td></tr><tr><td>Cooper Scoopers</td><td>Chattanooga TN</td><td>Weekly, one-time</td><td>Not listed</td><td>Residential, HOA, and commercial service</td></tr><tr><td>Scoop Smart</td><td>Chattanooga TN + North Georgia</td><td>Twice-weekly, weekly, every-other-week, monthly</td><td>Not listed</td><td>Monthly frequency option; broad area coverage</td></tr></tbody></table><h2>About Scoopy Doo</h2><p>Scoopy Doo is a locally owned pet waste removal company serving Chattanooga TN and North Georgia. Every visit includes an on-the-way text and a gate photo confirmation, and all waste is double-bagged into your outdoor bin, with haul-away available for $5 per visit. Service is available 7 days a week with no long-term contracts required. Free quotes at scoopychatt.com/quoterequest.</p>",
  '/doggy-doors': "<h1>Dog Door and Pet Door Installation in Chattanooga, TN and North Georgia</h1><p>Scoopy Doo Doggy Doors installs dog doors, also called pet doors or doggy doors, for homes in Chattanooga, TN and North Georgia. Every door is measured, installed, weather-sealed, and tested by the Scoopy Doo team. Good, Better, and Best options are offered at set prices, so there are no quote calls and no guessing on size. Pricing starts at $529, installed.</p><h2>Who installs pet doors in Chattanooga?</h2><p>Scoopy Doo LLC is a locally owned Chattanooga company that installs dog doors and pet doors across Chattanooga, TN and North Georgia. Scoopy Doo is not a national franchise or a national installer network. It is a local, family-run business with 90 five-star reviews and more than 150 active customers in the Chattanooga area, featured by the Chattanoogan in June 2026 and by WDEF News 12 in July 2026, and accredited by the Better Business Bureau. Scoopy Doo Doggy Doors is its professional dog door installation service.</p><h2>How does pet door installation work?</h2><p>There are three steps. First we measure your dog and the door, wall, or glass so the fit is right the first time. Then our team installs and weather-seals the door and tests it before we leave. Finally we clean up the work area and show you exactly how the new door works.</p><h2>What kinds of dog doors and pet doors does Scoopy Doo install?</h2><p>Scoopy Doo offers Good, Better, and Best options, covering soft flap pet doors, rigid locking panel doors, and smart app-controlled dog doors. Every option is professionally measured and installed for your dog, and can be fitted to a door, a wall, or glass.</p><h2>How much does dog door installation cost in Chattanooga?</h2><p>Pricing starts at $529, installed. Scoopy Doo prices dog door installation at a set price per option rather than a custom quote, so there is no phone call and no sales visit needed to get a number. Good, Better, and Best pricing is listed on the Scoopy Doo Doggy Doors page at scoopychatt.com/doggy-doors. Founding Customer pricing is available for the first 20 installs.</p><h2>Is there a pet door installer near me in Chattanooga or North Georgia?</h2><p>Scoopy Doo serves Chattanooga, TN and North Georgia, including Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, East Ridge, and Lookout Mountain TN, plus Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA. Scoopy Doo already runs regular service routes throughout this area every week.</p><h2>How do I get a dog door installed?</h2><p>Request installation at scoopychatt.com/doggy-doors. You can also reach Scoopy Doo at info@scoopychatt.com or 423-600-5040.</p>",
  '/': "<h1>Pet Waste Removal and Dog Poop Removal in Chattanooga, TN</h1><p>Scoopy Doo LLC is a locally owned pet waste removal and pooper scooper service based in Chattanooga, Tennessee, serving homes, HOAs, apartment communities, and commercial properties across the Chattanooga metro area and North Georgia. Scoopy Doo has 90 five-star reviews and more than 150 active clients, is accredited by the Better Business Bureau, and was featured by the Chattanoogan in June 2026 and by WDEF News 12 in July 2026. Scoopy Doo is also a member of aPaws, the Association of Professional Animal Waste Specialists. No contracts are required and service is available 7 days a week.</p><h2>What services does Scoopy Doo offer?</h2><p>Weekly dog poop removal is the most popular service. Scoopy Doo also offers twice-weekly service, every-other-week service, one-time yard cleanups, commercial pet waste removal for apartment complexes and businesses, and HOA common area cleanup. Scoopy Doo also installs dog doors and pet doors for homes in the same service area through Scoopy Doo Doggy Doors at scoopychatt.com/doggy-doors.</p><h2>How much does dog poop removal cost in Chattanooga?</h2><p>Weekly service starts at $20 per visit for one dog. Twice-weekly service is $18 per visit and every-other-week service starts at $33 per visit, each plus a small charge per additional dog. One-time yard cleanups start at $85, and optional waste takeaway is $5 per visit. Every quote is free and personalized to your yard size and number of dogs at scoopychatt.com/quoterequest. There are no contracts and no cancellation fees.</p><h2>What happens on every visit?</h2><p>You receive a text when your technician is on the way, so you do not need to be home. The technician searches the entire yard in a grid pattern, double-bags all waste, and places it in your outdoor bin, never at the gate; haul-away off the property is $5 per visit. After every visit your gate is secured and a photo confirmation is sent to your phone. Tools are sanitized between every yard.</p><h2>What areas does Scoopy Doo serve?</h2><p>In Tennessee: Chattanooga, Hixson, Red Bank, Signal Mountain, Lookout Mountain, Soddy-Daisy, Ooltewah, East Brainerd, East Ridge, Collegedale, Apison, Highland Park, and Downtown Chattanooga. In North Georgia: Ringgold, Rossville, Fort Oglethorpe, and Flintstone. North Georgia customers pay the same rates as Tennessee locations, with no extra fee for crossing the state line.</p><h2>How quickly can service start?</h2><p>Most new customers start within 2 to 5 days of requesting a quote, and Scoopy Doo responds the same day. Request a free quote at scoopychatt.com/quoterequest, email info@scoopychatt.com, or call 423-600-5040.</p>",
  '/dog-poop-removal-chattanooga': "<h1>Dog Poop Removal in Chattanooga, TN</h1><p>Scoopy Doo LLC provides professional dog poop removal for homes across Chattanooga, Tennessee and North Georgia. Service is available weekly, twice weekly, every other week, or as a single one-time cleanup, and no contract is required at any frequency.</p><h2>How much does dog poop removal cost in Chattanooga?</h2><p>Weekly service starts at $20 per visit for one dog. Twice-weekly service is $18 per visit and every-other-week service starts at $33 per visit, each plus a small charge for additional dogs. Quotes are free and based on your yard size and dog count at scoopychatt.com/quoterequest.</p><h2>How often should dog waste be removed?</h2><p>Weekly removal is the standard for households with one or two dogs. It keeps waste from accumulating, protects the lawn from nitrogen burn, and reduces the bacteria and parasites that build up in a yard between cleanings. Smaller yards and single-dog homes often do well on an every-other-week schedule.</p><h2>Is Scoopy Doo insured?</h2><p>Yes. Scoopy Doo LLC is fully insured on every visit, is accredited by the Better Business Bureau, and holds 90 five-star reviews across more than 150 active clients in the Chattanooga area. Call 423-600-5040 or email info@scoopychatt.com.</p>",
  '/pet-waste-removal-chattanooga': "<h1>Pet Waste Removal in Chattanooga, TN for Homes, HOAs, and Businesses</h1><p>Scoopy Doo LLC handles pet waste removal for residential yards, HOA common areas, apartment communities, and commercial properties throughout Chattanooga, Tennessee and North Georgia. Residential and commercial clients are both served on regular scheduled routes.</p><h2>Does Scoopy Doo work with HOAs and apartment communities?</h2><p>Yes. Scoopy Doo services shared green spaces, dog-walking paths, and pet waste stations, and can work directly with HOA boards and property managers on scheduling and invoicing. Consistent scheduled cleanup is the most reliable way for a community to stay compliant with its own pet waste rules.</p><h2>What does residential pet waste removal include?</h2><p>A technician searches the full yard in a grid pattern, double-bags everything found and places it in your outdoor bin. Waste is never left beside the gate. Haul-away off the property is $5 per visit. You get an on-the-way text before the visit and a gate photo confirmation after it.</p><h2>What does pet waste removal cost?</h2><p>Residential weekly service starts at $20 per visit for one dog, with twice-weekly at $18 per visit and every-other-week from $33 per visit. Commercial and HOA properties are quoted by site size and frequency. Request a free quote at scoopychatt.com/quoterequest.</p>",
  '/dog-poop-scooping-chattanooga': "<h1>Dog Poop Scooping Service in Chattanooga, TN</h1><p>Scoopy Doo LLC is a locally owned pooper scooper service in Chattanooga, Tennessee, serving the metro area and North Georgia 7 days a week. Scoopy Doo is not a national franchise. It is a family-run local business with 90 five-star reviews and more than 150 active clients.</p><h2>What happens during a scooping visit?</h2><p>You receive a text when the technician is on the way, so there is no need to be home as long as the gate is accessible. The technician walks the yard in a grid pattern so no section is missed, double-bags all waste, and removes it from the property. The gate is secured and photographed, and that photo is sent to your phone.</p><h2>Do you sanitize equipment between yards?</h2><p>Yes. Scooping tools are sanitized between every yard to avoid carrying bacteria or parasites from one property to the next.</p><h2>How do I start pooper scooper service?</h2><p>Request a free quote at scoopychatt.com/quoterequest. Scoopy Doo replies the same day and most new customers are on a route within 2 to 5 days. There are no contracts and no cancellation fees.</p>",
  '/yard-cleanup-chattanooga': "<h1>Yard Cleanup for Pet Owners in Chattanooga, TN</h1><p>Scoopy Doo LLC clears accumulated dog waste from Chattanooga and North Georgia yards in a single deep-clean visit. One-time cleanups suit spring cleaning, an overgrown yard after winter, preparing for a party, a move-out, or listing a home for sale.</p><h2>How much does a one-time yard cleanup cost?</h2><p>One-time cleanups start at $85, priced by yard size and how much waste has built up. Many customers book a one-time cleanup to reset the yard, then move onto weekly or every-other-week service from $20 per visit.</p><h2>What if the yard has not been cleaned in months?</h2><p>That is the normal case for a one-time cleanup. The technician grid-searches the entire yard, including wooded sections, tree lines, and areas under shrubs where waste is easy to miss. Everything is double-bagged and placed in your outdoor bin, never left at the curb. Haul-away off the property is $5 per visit.</p><h2>Why does built-up dog waste matter?</h2><p>Waste left on a lawn burns grass and damages soil, and it carries bacteria and parasites such as hookworms, roundworms, and giardia that persist in the yard. In heavy rain it washes into Chattanooga area waterways. Book a cleanup at scoopychatt.com/quoterequest or call 423-600-5040.</p>"
};

// Location data for static content generation
const LOC = {
  "chattanooga":      { name:"Chattanooga, TN",     desc:"Chattanooga is booming with new families, new neighborhoods, and a whole lot of dogs. Scoopy Doo is the local pet waste removal company keeping Chattanooga yards clean, safe, and ready for play, running regular routes throughout the city.", hoods:["North Shore","Highland Park","St. Elmo","Southside","Normal Park","Missionary Ridge","Brainerd","East Lake"], faqs:[["Do you service all Chattanooga neighborhoods?","Yes. We run regular routes across Chattanooga including North Shore, Highland Park, Missionary Ridge, St. Elmo, Normal Park, Brainerd, Southside, and more."],["How does the gate photo work?","After every visit we secure your gate and send a photo confirmation. You always know your yard was cleaned and your gate is closed."],["Do you remove the waste from the property?","All waste is double-bagged and placed in your outdoor bin, never left by the gate. If you would rather it not go in your own cans, waste takeaway is $5 per visit and we haul it off the property. Haul-away is included free on one-time cleanups."]] },
  "hixson":           { name:"Hixson, TN",           desc:"Hixson is one of Chattanooga's most established suburban communities with sprawling yards and lots of dogs. Scoopy Doo uses a systematic grid-pattern approach to find and remove all waste, even in wooded lots and near tree lines along Chickamauga Lake.",  hoods:["Middle Valley","Harrison","Town Creek","Shallowford Road","Curtain Pole Road","Wolftever Creek"], faqs:[["Do you service wooded yards in Hixson?","Absolutely. Our technicians use a systematic grid-pattern approach that covers your entire yard, including wooded sections and areas near tree lines."],["Do you remove the waste or leave bags at the gate?","We double-bag all waste and place it in your outdoor bin, never by your gate. Waste takeaway, where we haul it off the property instead, is $5 per visit and is included on one-time cleanups."],["Is there a contract?","No contracts, ever. You can start, pause, or cancel service at any time."]] },
  "red-bank":         { name:"Red Bank, TN",          desc:"Red Bank is a tight-knit city inside greater Chattanooga where neighbors know each other and community standards matter. Scoopy Doo serves Red Bank homeowners with reliable weekly pet waste removal, on-the-way texts, and gate photo confirmation after every visit.", hoods:["Red Bank proper","Dayton Pike area","Signal Mountain Road corridor","Ashland Terrace","Scenic View area"], faqs:[["Do you service all of Red Bank?","Yes. We service all Red Bank neighborhoods including areas along Dayton Pike, Signal Mountain Road, and surrounding residential streets."],["How often should I have service?","For one or two dogs, weekly service is the most popular option. It prevents waste from accumulating and keeps your yard clean and odor-free."],["Is your service reliable in winter?","Yes. We provide year-round service in Red Bank regardless of weather. We show up rain, cold, or shine."]] },
  "signal-mountain":  { name:"Signal Mountain, TN",   desc:"Signal Mountain properties have beautiful terrain and that same terrain makes pet waste cleanup genuinely difficult. Scoopy Doo is experienced with Signal Mountain yards - wooded lots, steep grades, and extensive ground cover - and uses a thorough grid-pattern approach to find and remove everything.", hoods:["Signal Mountain proper","Waldens Ridge","Signal Crest","James Boulevard corridor","Taft Highway area"], faqs:[["Do you service large or steeply graded properties?","Yes. Our technicians are experienced with Signal Mountain terrain including wooded sections, sloped yards, and large properties."],["Do you remove waste from the property?","Bags never stay at your gate. As standard we double-bag everything into your outdoor bin; add waste takeaway at $5 per visit and we remove it in our vehicle instead. One-time cleanups include haul-away."],["Is service available year-round?","Yes. We provide year-round service on Signal Mountain regardless of weather conditions."]] },
  "ooltewah":         { name:"Ooltewah, TN",          desc:"Ooltewah is one of the fastest-growing communities in the Chattanooga region with master-planned neighborhoods, active HOAs, and high standards for community appearance. Scoopy Doo helps Ooltewah families and HOA boards keep shared spaces and private yards consistently clean. We provide dependable dog poop pickup and pooper scooper service near Ooltewah, TN.", hoods:["Cambridge Square","Hamilton on Hunter","Snow Hill","Georgetown area","Windstone"], faqs:[["Do you serve HOAs and subdivisions in Ooltewah?","Yes. We service HOA common areas, green spaces, and dog-walking paths in Ooltewah subdivisions. We can work directly with HOA boards on scheduling and invoicing."],["Can Ooltewah service help avoid HOA violations?","Absolutely. Consistent professional cleanup is the most reliable way to stay compliant with HOA pet waste rules."],["Do you service Georgetown and Snow Hill areas?","Yes. We cover all major Ooltewah neighborhoods including Cambridge Square, Hamilton on Hunter, Snow Hill, Georgetown, and surrounding areas."]] },
  "east-brainerd":    { name:"East Brainerd, TN",     desc:"East Brainerd is one of Chattanooga's busiest suburban corridors - full of growing families, newer subdivisions, and busy schedules that leave no time for yard cleanup. Scoopy Doo keeps East Brainerd yards consistently clean with on-the-way texts and gate photo confirmation every visit.", hoods:["Gunbarrel Road area","Ooltewah-Georgetown Road","Camp Jordan vicinity","Jenkins Road corridor","East Brainerd Road subdivisions"], faqs:[["Do you service the subdivisions along Gunbarrel Road?","Yes. We have regular routes throughout East Brainerd including neighborhoods along Gunbarrel Road, Ooltewah-Georgetown Road, Jenkins Road, and surrounding areas."],["How do I get started?","Request a free quote online. We respond the same day and most new East Brainerd customers can start within 2-5 days."],["Do you handle overgrown yard cleanups?","Yes. If your yard has not been cleaned in a while, we offer one-time deep-clean visits to start fresh before setting up recurring service."]] },
  "soddy-daisy":      { name:"Soddy-Daisy, TN",       desc:"Soddy-Daisy stretches along beautiful Chickamauga Lake with a mix of lakefront homes and inland neighborhoods. Scoopy Doo provides consistent reliable pet waste pickup that keeps your yard clean and the lake healthy, serving Soddy-Daisy with regular routes and on-the-way texts every visit.", hoods:["Soddy-Daisy proper","Sequoyah Drive area","Chickamauga Lake shoreline","Dayton Pike corridor","Zion Hill Road area","Falling Water area"], faqs:[["Do you service lakefront properties in Soddy-Daisy?","Yes. We service lakefront and lake-view properties throughout Soddy-Daisy. Waterfront properties are one of the most important places to have consistent pet waste removal because of runoff."],["How does dog waste affect Chickamauga Lake?","Dog waste contains bacteria and pathogens that wash into the lake during rain. Regular professional cleanup significantly reduces contamination that reaches the water from your property."],["Can you service docks or lakeside areas?","Yes. We can clean yard areas leading to docks and waterfront access points, the areas closest to the water where cleanup matters most."]] },
  "east-ridge":       { name:"East Ridge, TN",         desc:"East Ridge sits on the Tennessee-Georgia border with a proud residential community that takes care of its neighborhoods. Scoopy Doo runs regular routes through East Ridge, keeping yards clean for families who want more time for the things they actually enjoy.", hoods:["Ringgold Road area","Cloud Springs Road","McBrien Road area","Bennett Road corridor","Spring Creek area"], faqs:[["Do you service East Ridge neighborhoods near the Georgia line?","Yes. East Ridge is well within our service area. We run regular routes throughout East Ridge including neighborhoods near the Georgia border."],["Can I get a one-time cleanup before starting regular service?","Yes. Many new customers start with a one-time deep clean to get the yard back to baseline, then move to weekly service."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all scooping tools between every yard to prevent the spread of bacteria and parasites."]] },
  "lookout-mountain": { name:"Lookout Mountain, TN",  desc:"Lookout Mountain is one of the most distinctive communities in the region with historic homes, sweeping properties, and terrain that makes DIY pet waste cleanup a real challenge. Scoopy Doo navigates the terrain carefully to deliver a thorough cleanup every visit.", hoods:["Lookout Mountain proper","Sunset Drive corridor","Ochs Highway area","Scenic Highway section","Bragg Avenue area"], faqs:[["Do you service Lookout Mountain properties?","Yes. We service Lookout Mountain properties including homes along Sunset Drive, Ochs Highway, Scenic Highway, and throughout the community."],["Can you handle terraced or steeply graded yards?","Yes. Our technicians are careful and thorough on terraced and sloped properties. We take the time to cover difficult terrain."],["How do you access gated properties?","Many Lookout Mountain clients provide a gate code at sign-up. We use it for every visit, close the gate after cleaning, and send a photo confirmation."]] },
  "ringgold":         { name:"Ringgold, GA",           desc:"Ringgold is the heart of Catoosa County about 15 miles south of Chattanooga. Scoopy Doo proudly serves Ringgold homeowners with professional pet waste removal, regular North Georgia routes, and no extra fees for Georgia locations. We handle dog poop removal across Ringgold and North Georgia (Catoosa and Walker counties) at no extra charge.", hoods:["Ringgold proper","Catoosa County subdivisions","Graysville Road area","Cloud Springs Road","Battlefield Parkway corridor"], faqs:[["Do you service Ringgold, GA?","Yes. Ringgold is one of our core service areas. We run regular routes throughout Ringgold and Catoosa County and do not charge extra for North Georgia locations."],["Is there any extra charge for Georgia locations?","No. Our pricing for Ringgold is the same as our Tennessee locations, based on yard size and number of dogs."],["How quickly can you start service?","Most Ringgold customers can be added to a route within 2-5 days of requesting a quote."]] },
  "rossville":        { name:"Rossville, GA",          desc:"Rossville sits right on the Tennessee-Georgia border moments from Chattanooga with established residential neighborhoods and a community that takes care of its properties. Scoopy Doo runs regular North Georgia routes and serves Rossville homeowners with reliable professional service.", hoods:["Rossville proper","McFarland Avenue area","Chickamauga Avenue corridor","Alabama Avenue area","North Georgia border neighborhoods"], faqs:[["Do you service Rossville, GA?","Yes. Rossville is within our North Georgia service area. We run regular routes and do not charge additional fees for Georgia locations."],["Do you service homes with multiple large dogs?","Absolutely. Multi-dog households are some of our best customers. Our pricing scales reasonably for additional dogs and we cover the full yard every visit."],["Do you remove the waste from the property?","We double-bag all waste and place it in your outdoor bin, never by your gate. If you would rather it not go in your cans, waste takeaway is $5 per visit."]] },
  "fort-oglethorpe":  { name:"Fort Oglethorpe, GA",   desc:"Fort Oglethorpe is one of the fastest-growing cities in North Georgia with new subdivisions, active HOAs, and families who want their neighborhoods to look great. Scoopy Doo serves Fort Oglethorpe with professional weekly and every-other-week pet waste removal and HOA common area service.", hoods:["Fort Oglethorpe proper","Battlefield Parkway corridor","Barnhardt Road area","Chickamauga Battlefield vicinity","LaFayette Road area","Parker Drive corridor"], faqs:[["Do you service Fort Oglethorpe, GA?","Yes. Fort Oglethorpe is within our regular North Georgia service area. We run established routes and do not charge extra for Catoosa County locations."],["Do you work with HOAs in Fort Oglethorpe?","Yes. We service HOA common areas, dog-walking paths, and pet waste stations throughout Fort Oglethorpe."],["Do you service newer Fort Oglethorpe subdivisions?","Yes. We actively service newer developments along Battlefield Parkway, Barnhardt Road, LaFayette Road, and other growing corridors."]] },
  "apison":           { name:"Apison, TN",             desc:"Apison is one of Hamilton County's fast-growing communities with newer residential developments and larger lots. Scoopy Doo handles the whole yard every visit using a grid-pattern approach, making professional cleanup especially valuable for larger properties with multiple dogs.", hoods:["Apison Pike corridor","Standifer Gap Road area","Hamilton County rural east","Harrison vicinity","East Hamilton corridor"], faqs:[["Do you service Apison, TN?","Yes. Apison is within our East Hamilton County service area. We run regular routes and can typically start new customers within 2-5 days."],["Do you offer pricing for multiple dogs?","Yes. Our pricing scales affordably for households with multiple dogs. Request a free quote for your exact pricing."],["Can you handle larger lots?","Absolutely. We service a range of property sizes including larger lots typical in the Apison area and use a grid approach to cover every section."]] },
  "collegedale":      { name:"Collegedale, TN",        desc:"Collegedale is a small community-focused city east of Chattanooga with well-maintained neighborhoods and high standards for appearance. Scoopy Doo serves Collegedale families with reliable weekly and every-other-week pet waste removal with consistent scheduling and no hidden fees.", hoods:["Collegedale proper","Southern Adventist University area","McDonald Road corridor","Apison Pike vicinity","East Hamilton corridor"], faqs:[["Do you service Collegedale, TN?","Yes. Collegedale is within our East Hamilton County service area. We run regular routes and do not charge extra for East Hamilton County locations."],["Are there any hidden fees?","No hidden fees. Our pricing is based on yard size and number of dogs. No fuel surcharges, no seasonal fees."],["How consistent is the schedule?","You are assigned a regular day and we show up on that day every week or every-other-week. You get an on-the-way text before each visit."]] },
  "st-elmo": { name:"St. Elmo, TN", desc:"St. Elmo sits at the foot of Lookout Mountain, where Victorian-era homes, deep shaded lots, and a genuinely walkable street grid make it one of Chattanooga's most distinctive neighborhoods. Mature trees and older fencing mean yards here hold moisture and leaf cover, which hides waste until it becomes a problem. Scoopy Doo runs regular St. Elmo routes and sweeps the whole yard in a grid pattern so nothing gets missed under the canopy.", hoods:["St. Elmo Avenue corridor", "Incline Railway area", "Alabama Avenue", "Virginia Avenue", "Guild Street area", "Ochs Highway vicinity"], faqs:[["Do you serve St. Elmo?","Yes. St. Elmo is an established part of our Chattanooga service area and we run regular routes through the neighborhood. There is no travel surcharge for St. Elmo addresses."],["Can you work with older fencing and gates in St. Elmo?","Yes. Many St. Elmo homes still have their original fencing and narrow side gates. We work with whatever setup you have, always latch the gate behind us, and send a photo confirmation after every visit."],["How often should I schedule service in St. Elmo?","Weekly is the most popular choice here. Heavy tree cover keeps St. Elmo yards damp and shaded, which slows decomposition and holds odor, so weekly pickup keeps things under control better than every-other-week."],["Do I need to be home for a St. Elmo visit?","No. You get a text when we are on the way, we clean the yard, close the gate, and send a photo when we finish. Most of our St. Elmo customers are at work when we come through."]] },
  "north-chattanooga": { name:"North Chattanooga, TN", desc:"North Chattanooga, the Northshore, is one of the most dog-heavy parts of the city. Between Coolidge Park, the riverwalk, and the Frazier Avenue district, this is a neighborhood where people walk their dogs constantly and expect their own yards to be just as clean. Scoopy Doo services Northshore homes on weekly, twice-weekly, and every-other-week schedules with no contract required.", hoods:["Frazier Avenue district", "Coolidge Park area", "Cherokee Boulevard", "Hill City", "Manufacturers Road corridor", "Tremont Street area"], faqs:[["Do you serve North Chattanooga and the Northshore?","Yes. North Chattanooga is one of our core Chattanooga neighborhoods and we run regular routes there every week. Northshore addresses are covered at standard rates."],["Do you handle small Northshore yards?","Yes. Most Northshore lots are compact, and small yards are actually where weekly service matters most, because waste concentrates fast and there is nowhere for it to go unnoticed."],["Can you access a yard through an alley or shared drive?","Yes. A lot of North Chattanooga properties are accessed from the rear or from a shared drive. Tell us how to get in when you request your quote and we will route around it."],["Do you offer twice-weekly service in North Chattanooga?","Yes. Twice-weekly is a popular option on the Northshore for households with two or more dogs on a small lot. It runs at a lower per-visit rate than weekly service."]] },
  "southside": { name:"Southside, Chattanooga TN", desc:"The Southside, centered on the Main Street district, is where converted warehouses, infill townhomes, and courtyard-sized yards sit alongside some of the city's busiest restaurants. Yard space here is at a premium, which makes pet waste far more noticeable than it would be on a larger lot. Scoopy Doo cleans Southside courtyards, small fenced yards, and shared pet areas on a schedule that fits the property.", hoods:["Main Street district", "Jefferson Heights", "Cowart Street area", "Chestnut Street corridor", "Blue Goose Hollow", "Broad Street south end"], faqs:[["Do you service Southside courtyards and small yards?","Yes. Courtyards, small fenced yards, and turf strips are all standard for us. Smaller spaces usually need a tighter schedule because waste concentrates faster with nowhere to spread out."],["Can you service a shared pet area for a Southside building?","Yes. We service shared pet areas and pet relief areas for buildings and communities in addition to individual residences. Commercial and multi-unit pricing is quoted per property."],["Do you serve the Main Street district?","Yes. The Main Street district and the surrounding Southside blocks are all within our Chattanooga service area at standard residential rates."],["How do you handle waste on a property with no yard bin?","We double-bag everything and haul it completely off the property. Nothing goes into your bin or a shared dumpster, which is the setup most Southside residents want."]] },
  "lookout-valley": { name:"Lookout Valley, TN", desc:"Lookout Valley sits west of Lookout Mountain along the I-24 corridor, where lots run considerably larger than they do in the city and yards back up to woods and open ground. Bigger yards are not easier yards - waste spreads across more area and is harder to find in tall grass and leaf litter. Scoopy Doo sweeps Lookout Valley properties in a full grid pattern so a large yard gets covered end to end.", hoods:["Cummings Highway corridor", "Browns Ferry Road area", "Wauhatchie", "Elder Mountain vicinity", "Tiftonia", "Old Wauhatchie Pike"], faqs:[["Do you serve Lookout Valley?","Yes. Lookout Valley is within our standard Chattanooga service area, including the Cummings Highway and Browns Ferry Road corridors, at no additional travel charge."],["Do you charge more for a large Lookout Valley yard?","Pricing is based on yard size and number of dogs, so a larger property can price above the starting rate. Every quote is free and specific to your yard - there are no surprise charges after the fact."],["Can you clean up a yard that has been neglected for months?","Yes. That is what our one-time cleanup is for, and it is a common starting point for larger Lookout Valley properties. Most customers then move onto a weekly or every-other-week schedule to keep it that way."],["Do you cover wooded edges and drainage areas?","Yes. We sweep the usable yard in a grid pattern including the edges where waste tends to collect. If there is a specific area of the property you want left alone, tell us and we will skip it."]] },
  "riverview": { name:"Riverview, Chattanooga TN", desc:"Riverview is one of Chattanooga's most established neighborhoods, with mature lawns, generous setbacks, and properties that are visibly well kept. Homeowners here care how the yard reads from the street and from the patio, and pet waste undercuts that faster than almost anything else. Scoopy Doo provides quiet, consistent service that keeps a Riverview lawn presentable without anyone having to think about it.", hoods:["Riverview proper", "Barton Avenue area", "Hixson Pike corridor", "Chattanooga Golf and Country Club vicinity", "Minnekahda", "Dartmouth Street area"], faqs:[["Do you serve Riverview?","Yes. Riverview is part of our regular Chattanooga routes and is covered at standard rates with no travel surcharge."],["Will pet waste damage my lawn?","Yes, it will. Dog waste is high in nitrogen and salts, which burns turf and leaves dead patches that take a full season to recover. Removing it consistently is the simplest way to protect an established Riverview lawn."],["How discreet is the service?","Very. You get a text when we are on the way, we clean the yard, secure the gate, and send a photo when we leave. There is no door knock and no need for you to be home."],["Do you offer service for larger Riverview lots?","Yes. Pricing scales with yard size and number of dogs, and larger lots are quoted individually. The quote is free and you will know the exact rate before any service starts."]] },
  "normal-park": { name:"Normal Park, Chattanooga TN", desc:"Normal Park is a family neighborhood in North Chattanooga where the yards get heavy use - kids, dogs, and often both at once. That is precisely the situation where pet waste stops being a chore and starts being a health question, because roundworm and hookworm eggs persist in soil long after the waste itself is gone. Scoopy Doo keeps Normal Park yards clean weekly so the yard stays usable for everyone in the house.", hoods:["Normal Park school area", "Mississippi Avenue", "Colville Street area", "Dallas Road corridor", "Bell Avenue", "Hamilton Avenue vicinity"], faqs:[["Do you serve Normal Park?","Yes. Normal Park is part of our regular North Chattanooga routes and is covered at standard rates."],["Is pet waste actually a health risk for kids?","It can be. Dog waste can carry roundworms, hookworms, giardia, and bacteria such as E. coli, and some of those eggs stay viable in soil for months after the waste is gone. Consistent removal is the practical way to reduce that exposure in a yard children use."],["Do you sanitize your equipment between yards?","Yes. Scooping tools and footwear are sanitized between every property we visit, which keeps us from moving parasites or bacteria from one yard into the next."],["What if the kids leave toys in the yard?","Not a problem. We work around whatever is in the yard and never move or discard personal items. If something needs to stay untouched, mention it when you book."]] },
  "brainerd": { name:"Brainerd, Chattanooga TN", desc:"Brainerd is a long-established East Chattanooga neighborhood built largely around mid-century ranch homes with flat, open, fenced back yards. Those yards are straightforward to service and easy to keep spotless on a weekly schedule, which is why Brainerd is one of our most efficient routes. Scoopy Doo offers weekly, twice-weekly, every-other-week, and one-time cleanups throughout the area.", hoods:["Brainerd Road corridor", "Eastgate area", "Belvoir", "Brainerd Hills", "Moore Road area", "Germantown Road vicinity"], faqs:[["Do you serve Brainerd?","Yes. Brainerd is one of our established Chattanooga service areas, including the Brainerd Road corridor and the surrounding residential streets, at standard rates."],["Is Brainerd different from East Brainerd for service?","They are two separate areas and we serve both. Brainerd sits closer to the city along Brainerd Road, while East Brainerd is further out toward Ooltewah. Pricing is the same for either."],["What if my yard has not been cleaned in months?","Start with a one-time cleanup. We reset the entire yard first, then you can move onto a weekly or every-other-week schedule to keep it that way. One-time cleanups are priced by yard size and how much has accumulated."],["Do you service fully fenced back yards when nobody is home?","Yes, and that is how most of our Brainerd visits work. You get a text when we are on the way, we clean, we latch the gate, and you get a photo of the closed gate when we are done."]] },
  "highland-park":    { name:"Highland Park, TN",      desc:"Highland Park is one of Chattanooga's most vibrant historic neighborhoods with tree-lined streets, revitalized bungalows, and neighbors who care about their blocks. Scoopy Doo runs regular Chattanooga routes through Highland Park, providing reliable urban yard cleanup.", hoods:["Highland Park proper","McCallie Avenue corridor","Third Street area","Dodds Avenue vicinity","Glass Street area","Orchard Knob nearby"], faqs:[["Do you service small urban yards in Highland Park?","Yes. We service yards of all sizes including the smaller urban lots typical in Highland Park. Smaller yards often mean waste is more concentrated and more important to keep clean consistently."],["How often should I have service?","For most Highland Park households with one or two dogs, weekly service is the best choice. Smaller yards fill up quickly and weekly pickup keeps odor and accumulation under control."],["Is Highland Park within the Chattanooga service area?","Yes. Highland Park is one of our established Chattanooga neighborhoods. We run regular city routes and Highland Park is well within our coverage area."]] },
  "flintstone":       { name:"Flintstone, GA",         desc:"Flintstone is a Walker County community in the hills of North Georgia with a mix of rural homesteads and established residential neighborhoods. Scoopy Doo serves Flintstone as part of our North Georgia coverage with no extra Walker County fees.", hoods:["Flintstone proper","US-27 corridor","Walker County residential","Lookout Valley vicinity","Cloud Springs Road area"], faqs:[["Do you service Flintstone, GA?","Yes. Flintstone is within our North Georgia service coverage. We do not charge extra fees for Walker County locations. Pricing is based on yard size and number of dogs."],["Do you sanitize your equipment between yards?","Yes, always. We sanitize all tools and footwear between every single yard to prevent the spread of bacteria and parasites."],["Can you handle larger rural properties?","Yes. We service a range of property sizes including larger rural lots and use a grid-pattern approach to make sure nothing is missed."]] },
  "downtown":         { name:"Downtown Chattanooga, TN", desc:"Downtown Chattanooga is one of the most walkable dog-friendly urban environments in Tennessee. Scoopy Doo provides professional pet waste removal for downtown homes, condos with private outdoor spaces, and townhomes throughout the core and adjacent neighborhoods.", hoods:["Downtown proper","Bluff View","Southside","MLK District","North Shore","Riverfront area"], faqs:[["Do you service downtown Chattanooga homes and condos?","Yes. We service private yards, townhome outdoor spaces, and residential properties throughout downtown Chattanooga and adjacent neighborhoods including Southside, Bluff View, and the MLK District."],["Why does pet waste matter near the Tennessee River?","Storm drains in downtown Chattanooga connect directly to the Tennessee River. Dog waste washes into the water during rain, contributing bacteria and pathogens that affect water quality."],["How often should downtown properties be cleaned?","Weekly service is most popular for downtown properties. Compact yards with dogs fill up quickly and weekly pickup keeps the space pleasant year-round."]] }
};

function makeLocContent(slug) {
  var d = LOC[slug];
  if (!d) return "";
  var h = "<h1>Dog Poop Removal in " + d.name + " | Scoopy Doo Pet Waste Removal</h1>";
  h += "<p>" + d.desc + "</p>";
  h += "<h2>Neighborhoods We Serve in " + d.name + "</h2><ul>";
  d.hoods.forEach(function(n){ h += "<li>" + n + "</li>"; });
  h += "</ul>";
  h += "<h2>Frequently Asked Questions</h2>";
  d.faqs.forEach(function(f){ h += "<h3>" + f[0] + "</h3><p>" + f[1] + "</p>"; });
  h += "<p>Get a free quote at scoopychatt.com/quoterequest. We respond the same day.</p>";
  return h;
}

// FAQPage schema for /faq route
const SCHEMA = {
  '/faq': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"How much does dog poop removal cost in Chattanooga?","acceptedAnswer":{"@type":"Answer","text":"Scoopy Doo pricing depends on yard size and number of dogs. Every quote is free and personalized at scoopychatt.com/quoterequest. There are no long-term contracts."}},{"@type":"Question","name":"How often does Scoopy Doo come to clean?","acceptedAnswer":{"@type":"Answer","text":"Weekly and every-other-week service is available. Weekly is the most popular option for one or two dogs. One-time cleanups are also available."}},{"@type":"Question","name":"Does Scoopy Doo serve North Georgia?","acceptedAnswer":{"@type":"Answer","text":"Yes. Scoopy Doo serves Ringgold, Rossville, Fort Oglethorpe, and Flintstone in Catoosa and Walker counties Georgia, at the same rates as Tennessee locations."}},{"@type":"Question","name":"What happens during a pet waste removal visit?","acceptedAnswer":{"@type":"Answer","text":"You receive a text when the technician is on the way. The technician cleans the entire yard, secures the gate, and sends a photo confirmation. Waste is double-bagged and placed in your outdoor bin, or hauled off the property for $5 per visit."}},{"@type":"Question","name":"Is there a contract for Scoopy Doo service?","acceptedAnswer":{"@type":"Answer","text":"No contracts, ever. You can start, pause, or cancel service at any time with no cancellation fees."}},{"@type":"Question","name":"Does Scoopy Doo sanitize equipment between yards?","acceptedAnswer":{"@type":"Answer","text":"Yes. All scooping tools and footwear are sanitized between every yard to prevent the spread of bacteria and parasites."}},{"@type":"Question","name":"Does Scoopy Doo remove waste from the property?","acceptedAnswer":{"@type":"Answer","text":"Waste is double-bagged and placed in your outdoor bin, never by the gate. Haul-away off the property is $5 per visit, and is included on one-time cleanups."}},{"@type":"Question","name":"How do I get started with Scoopy Doo?","acceptedAnswer":{"@type":"Answer","text":"Request a free quote at scoopychatt.com/quoterequest. Most new customers can start within 2-5 days."}}]}</script>'
,
  '/services': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Pet Waste Removal Services - Scoopy Doo LLC","description":"Weekly, twice-weekly, every-other-week, and one-time pet waste removal for homes, HOAs, and commercial properties in Chattanooga TN and North Georgia.","url":"https://www.scoopychatt.com/services","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/dog-poop-removal-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Dog poop removal","name":"Dog Poop Removal - Scoopy Doo LLC","description":"Professional dog poop removal for homes, HOAs, and commercial properties in Chattanooga TN and North Georgia. Weekly, twice-weekly, every-other-week, and one-time cleanups with on-the-way texts and gate photo confirmation.","url":"https://www.scoopychatt.com/dog-poop-removal-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/pet-waste-removal-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Pet Waste Removal - Scoopy Doo LLC","description":"Full-service pet waste removal in Chattanooga TN and North Georgia with weekly, twice-weekly, every-other-week, and one-time visits. All waste is double-bagged and placed in your outdoor bin, or hauled off the property for $5 per visit.","url":"https://www.scoopychatt.com/pet-waste-removal-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/dog-poop-scooping-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Pooper scooper service","name":"Dog Poop Scooping - Scoopy Doo LLC","description":"Reliable pooper scooper service in Chattanooga TN and North Georgia. Every visit includes a full yard sweep in a grid pattern and a gate photo confirmation when the job is done.","url":"https://www.scoopychatt.com/dog-poop-scooping-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/yard-cleanup-chattanooga': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Dog waste yard cleanup","name":"Dog Waste Yard Cleanup - Scoopy Doo LLC","description":"One-time and recurring dog waste yard cleanup in Chattanooga TN and North Georgia. No contracts required and free quotes online.","url":"https://www.scoopychatt.com/yard-cleanup-chattanooga","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/one-time-cleanup': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"One-time yard cleanup","name":"One-Time Yard Cleanup - Scoopy Doo LLC","description":"One-time deep cleanup of accumulated dog waste starting at $85 for homes in Chattanooga TN and North Georgia. No ongoing commitment required.","url":"https://www.scoopychatt.com/one-time-cleanup","provider":{"@type":"ProfessionalService","name":"Scoopy Doo LLC","url":"https://www.scoopychatt.com","telephone":"+14236005040"},"areaServed":"Chattanooga TN and North Georgia"}</script>',
  '/doggy-doors': '<script type="application/ld+json">{"@context":"https://schema.org","@type":"Service","serviceType":"Dog door and pet door installation","name":"Dog Door and Pet Door Installation - Scoopy Doo LLC","description":"Professional dog door and pet door installation for homes in Chattanooga TN and North Georgia. Doors are measured, installed, weather-sealed, and tested by the Scoopy Doo team, with Good, Better, and Best options at set prices.","url":"https://www.scoopychatt.com/doggy-doors","provider":{"@id":"https://www.scoopychatt.com/#business"},"areaServed":"Chattanooga TN and North Georgia","offers":{"@type":"AggregateOffer","lowPrice":"529","priceCurrency":"USD","availability":"https://schema.org/InStock","description":"Dog door installation starting at 529 dollars, installed"}}</script><script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Who installs dog doors and pet doors in Chattanooga TN?","acceptedAnswer":{"@type":"Answer","text":"Scoopy Doo LLC installs dog doors and pet doors in Chattanooga TN and North Georgia. Scoopy Doo is a locally owned family-run company, not a national franchise, with 90 five-star reviews and more than 150 active customers in the Chattanooga area."}},{"@type":"Question","name":"How does pet door installation work?","acceptedAnswer":{"@type":"Answer","text":"Scoopy Doo measures your dog and the door, wall, or glass so the fit is correct, installs and weather-seals the door, tests it, then cleans up the work area and shows you how it works."}},{"@type":"Question","name":"How much does dog door installation cost in Chattanooga?","acceptedAnswer":{"@type":"Answer","text":"Pricing starts at 529 dollars, installed. Scoopy Doo uses set pricing per option rather than a custom quote, so no phone call or sales visit is needed. Good, Better, and Best pricing is listed at scoopychatt.com/doggy-doors, with Founding Customer pricing for the first 20 installs."}},{"@type":"Question","name":"What areas does Scoopy Doo install dog doors in?","acceptedAnswer":{"@type":"Answer","text":"Chattanooga TN and North Georgia, including Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Soddy-Daisy, East Ridge, and Lookout Mountain TN, plus Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA."}}]}</script>'
};

const routes = {
  '/press': ['Scoopy Doo in the News | Press and Media Coverage | Chattanooga Pet Waste Removal', 'See news coverage of Scoopy Doo LLC, the largest pet waste removal company in the Chattanooga area. Featured in the Chattanoogan and on WDEF News 12.'],
  '/': ['Pet Waste Removal & Dog Poop Removal | Chattanooga TN | Scoopy Doo', 'Pet waste removal & dog poop pickup in Chattanooga TN & North Georgia. 5-star rated with 90+ Google reviews. Weekly service from $20 per visit. Free quotes.'],
  '/services': ['Pet Waste Removal Services in Chattanooga, TN | Scoopy Doo', 'Weekly, every-other-week & one-time dog poop removal in Chattanooga. See what Scoopy Doo offers and book today.'],
  '/podcast': ["The Scoopy Doo Podcast | Chattanooga Pet Waste Removal", "Behind the scenes of Scoopy Doo LLC, the father-daughter pet waste removal company serving Chattanooga TN and North Georgia."],
  '/near-me': ['Pooper Scooper Service Near Me in Chattanooga, TN', 'Looking for a pooper scooper service near you in Chattanooga? Scoopy Doo offers reliable local dog waste removal.'],
  '/one-time-cleanup': ['One-Time Dog Poop Cleanup in Chattanooga, TN | Scoopy Doo', 'Get a one-time dog poop cleanup in Chattanooga, TN. Perfect for spring cleaning or first-time service.'],
  "/cost-calculator": ["Dog Poop Cost Calculator | Chattanooga TN | Scoopy Doo", "Estimate weekly, twice-weekly, and one-time pooper scooper pricing in Chattanooga and North Georgia, then get a free exact quote from Scoopy Doo."],
  '/how-it-works': ['How It Works | Scoopy Doo Pet Waste Removal Chattanooga', 'Easy online quotes, secure online payment, on-the-way texts, and gate photo proof after every visit. Working with Scoopy Doo is simple.'],
  '/comparison': ['Pet Waste Removal Services Compared - Chattanooga TN 2026 | Scoopy Doo', 'Side-by-side comparison of Chattanooga pet waste removal services: Scoopy Doo, PooTagic, Doo Doo Blues, Scoop Smart, and more. Updated June 2026.'],
  '/doggy-doors': ['Dog Door & Pet Door Installation in Chattanooga, TN | Scoopy Doo', 'Dog door and pet door installation in Chattanooga, TN and North Georgia. Locally owned, not a franchise. Set pricing from $529 installed, no quote calls.'],
  '/dog-poop-removal-chattanooga': ['Dog Poop Removal in Chattanooga, TN | Scoopy Doo LLC', 'Professional dog poop removal in Chattanooga, TN. Dependable weekly service, fully insured.'],
  '/pet-waste-removal-chattanooga': ['Pet Waste Removal in Chattanooga, TN | Scoopy Doo', 'Expert pet waste removal in Chattanooga, TN for homes, HOAs & businesses. Request a free quote.'],
  '/dog-poop-scooping-chattanooga': ['Dog Poop Scooping Service in Chattanooga, TN | Scoopy Doo', 'Reliable dog poop scooping in Chattanooga, TN. Weekly and every-other-week pooper scooper service.'],
  '/yard-cleanup-chattanooga': ['Yard Cleanup for Pet Owners in Chattanooga, TN | Scoopy Doo', 'Complete yard cleanup for pet owners in Chattanooga, TN. Book a one-time or recurring cleanup.'],
  '/service-areas': ['Service Areas | Pet Waste Removal Around Chattanooga, TN', 'Scoopy Doo serves Chattanooga and surrounding areas. See the neighborhoods we cover.'],
  '/about': ['About Scoopy Doo | Chattanooga Pet Waste Removal', "Meet Scoopy Doo LLC, Chattanooga's locally owned pet waste removal company."],
  '/faq': ['Pet Waste Removal FAQs | Scoopy Doo Chattanooga', 'Answers to common questions about dog poop removal in Chattanooga: pricing, scheduling, and more.'],
  '/quote': ['Get a Free Pet Waste Removal Quote | Chattanooga, TN', 'Get a fast, free quote for dog poop removal in Chattanooga, TN.'],
  '/spring-special': ['Spring Special: Buy 2 Months, Get 1 Free | Scoopy Doo', 'Limited-time Chattanooga spring special from Scoopy Doo.'],
  '/pet-safe-checklist': ['Pet-Safe Yard Checklist | Scoopy Doo Chattanooga', 'A free pet-safe yard checklist for Chattanooga dog owners.'],
  '/dog-park-guide': ['Chattanooga Dog Park Guide for Dog Owners | Scoopy Doo', "Discover Chattanooga's best dog parks. A local guide from Scoopy Doo."],
  '/blog': ['Pet Waste & Dog Care Blog | Scoopy Doo Chattanooga', 'Tips on pet waste removal, yard health, and dog care for Chattanooga homeowners.'],
  '/privacy-policy': ['Privacy Policy | Scoopy Doo LLC', 'Privacy policy for Scoopy Doo LLC.'],
  '/terms-of-service': ['Terms of Service | Scoopy Doo LLC', 'Terms of service for Scoopy Doo LLC pet waste removal.'],
  '/blog/professional-waste-removal-benefits': ['Benefits of Professional Pet Waste Removal | Scoopy Doo Chattanooga', 'Why professional dog waste removal is safer and more thorough than DIY. Scoopy Doo serves Chattanooga and surrounding areas weekly.'],
  '/blog/winter-dog-poop-cleanup-chattanooga': ['Winter Dog Poop Cleanup in Chattanooga | Scoopy Doo', 'Cold weather does not stop dog waste from piling up. Learn why Chattanooga yards need winter pet waste removal and what Scoopy Doo service costs from 18 dollars a visit.'],
  '/blog/seasonal-pet-care-tips': ['Seasonal Pet Care Tips for Chattanooga Dog Owners | Scoopy Doo', 'Keep your yard clean and safe year-round with seasonal pet waste tips from Scoopy Doo LLC in Chattanooga, TN.'],
  '/blog/health-benefits-yard-cleanup': ['Health Benefits of Regular Yard Cleanup for Pet Owners | Scoopy Doo', 'Regular dog waste removal protects your family from bacteria and parasites. Learn why weekly cleanup matters for Chattanooga homeowners.'],
  '/blog/customer-success-stories': ['Customer Success Stories | Scoopy Doo Pet Waste Removal Chattanooga', 'Real stories from Chattanooga homeowners and HOAs who rely on Scoopy Doo for weekly pet waste removal.'],
  '/blog/diy-vs-professional': ['DIY vs Professional Dog Waste Removal | Scoopy Doo Chattanooga', 'Compare DIY pet waste cleanup to professional pooper scooper service in Chattanooga, TN. See which option saves time and money.'],
  '/blog/lawn-health-and-pet-waste': ['How Pet Waste Affects Your Lawn Health | Scoopy Doo Chattanooga', 'Dog waste kills grass and harms soil. Learn how regular professional cleanup protects your Chattanooga lawn from long-term damage.'],
  '/blog/health-risks-of-pet-waste': ['Health Risks of Unmanaged Pet Waste | Scoopy Doo Chattanooga', 'Dog waste carries bacteria, hookworms, roundworms, and giardia. Learn the health risks and how Scoopy Doo protects Chattanooga families.'],
  '/blog/pet-waste-management-guide': ['The Complete Pet Waste Management Guide for Dog Owners | Scoopy Doo', 'Everything Chattanooga dog owners need about pet waste management - frequency, disposal, health risks, and professional service options.'],
  '/blog/how-often-scoop-dog-poop-chattanooga': ['How Often Should You Scoop Dog Poop in Chattanooga? | Scoopy Doo', 'Weekly scooping is the gold standard. Learn why cleanup frequency matters for lawn health and family safety in Chattanooga, TN.'],
  '/blog/spring-pet-care-checklist': ['Spring Pet Care Checklist for Chattanooga Dog Owners | Scoopy Doo', 'Spring in Chattanooga means wet yards hiding months of pet waste. Use this checklist to get your yard cleaned up and ready.'],
  '/blog/is-dog-waste-bad-for-lawn': ['Is Dog Waste Bad for Your Lawn? | Scoopy Doo Chattanooga', 'Yes - dog waste kills grass and damages soil. Learn what it does to your Chattanooga yard and how professional cleanup helps.'],
  '/blog/best-pooper-scooper-services-chattanooga': ['Best Pooper Scooper Services in Chattanooga, TN | Scoopy Doo', 'Looking for the best dog poop removal in Chattanooga? Online quotes, on-the-way texts, gate photo confirmation. No contracts.'],
  '/blog/is-dog-poop-hurting-your-chattanooga-yard': ['Is Dog Poop Hurting Your Chattanooga Yard? | Scoopy Doo', 'Dog waste damages grass and soil over time. Find out if your Chattanooga yard is being harmed and how Scoopy Doo can help.'],
  '/blog/chattanooga-pet-waste-removal-homeowners': ['Pet Waste Removal Guide for Chattanooga Homeowners | Scoopy Doo', 'A complete guide for Chattanooga homeowners on pet waste management - health risks, lawn damage, waterway protection, and professional service.'],
  '/blog/commercial-pet-waste-removal-chattanooga': ['Commercial Pet Waste Removal in Chattanooga, TN | Scoopy Doo', 'Professional pet waste removal for apartments, HOAs, and businesses in Chattanooga. Flexible scheduling, no contracts.'],
  '/blog/fall-yard-care-checklist-chattanooga': ['Fall Yard Care Checklist for Chattanooga Dog Owners | Scoopy Doo', 'A fall pet waste and yard care checklist for Chattanooga dog owners. Learn why leaf season makes cleanup harder and how professional dog poop removal helps.'],
  '/blog/how-often-clean-yard': ['How Often Should You Clean Your Yard of Dog Waste? | Scoopy Doo', 'Weekly is the gold standard. Learn the right cleanup frequency based on your dog count, yard size, and Chattanooga season.'],
  '/blog/podcast-blog': ['Scoopy Doo on the Podcast | The Chattanooga Pet Waste Removal Story', 'Hear the Scoopy Doo LLC founder discuss starting a pet waste removal business in Chattanooga, TN.'],
  '/blog/signal-mountain': ['Pet Waste Removal Tips for Signal Mountain, TN | Scoopy Doo Blog', 'Scoopy Doo serves Signal Mountain with thorough yard cleanup. We handle larger lots and wooded terrain every week.'],
  '/blog/dog-poop-cleanup-chattanooga-summer-heat': ['Dog Poop Cleanup in Chattanooga During Hot, Humid Weather | Scoopy Doo', 'Summer heat and humidity make dog waste more dangerous. Learn why Chattanooga yards need regular cleanup during the hot months and how Scoopy Doo can help.'],
  '/blog/dog-poop-laws-chattanooga': ['Is It Illegal to Not Pick Up Dog Poop in Chattanooga? | Scoopy Doo', 'Yes, Chattanooga law requires dog owners to pick up after their pets. Here is what City Code Chapter 7 says, the fines you could face, and how to stay compliant.'],
  '/blog/soddy-daisy': ['Pet Waste Removal in Soddy-Daisy, TN | Scoopy Doo Blog', 'Scoopy Doo serves Soddy-Daisy and Chickamauga Lake area homeowners. Waterfront cleanup protects the lake and your family.'],
  '/blog/one-time-dog-poop-cleanup-chattanooga': ['One-Time Dog Poop Cleanup in Chattanooga: Cost & How It Works | Scoopy Doo', 'What a one-time dog poop cleanup costs in Chattanooga, when to book one, and how it works. One-time yard cleanups from $85 with no contract. Call 423-600-5040.'],
  '/blog/hoa-pet-waste-removal-chattanooga': ['HOA Pet Waste Removal in Chattanooga: A Board Guide | Scoopy Doo', 'How HOA and community pet waste removal works in Chattanooga: what is included, how pricing is quoted, and how to set up service for common areas and dog stations. Call 423-600-5040.'],
  '/blog/dog-door-installation-chattanooga': ['Dog Door Installation in Chattanooga, TN: Cost & Guide | Scoopy Doo', 'How much does dog door installation cost in Chattanooga? Good, Better, and Best options from $529 installed, professionally measured, sealed, and tested. Call 423-600-5040.'],
  '/blog/weekly-vs-biweekly-dog-poop-service-chattanooga': ['Weekly vs Every-Other-Week Dog Poop Service in Chattanooga | Scoopy Doo', 'Weekly dog poop removal in Chattanooga is $20 per visit and every-other-week is $33 per visit, about $15 a month apart for twice the visits. How to pick the right schedule.'],
  '/blog/pet-waste-stations-apartments-hoas-chattanooga': ['Pet Waste Stations for Chattanooga Apartments and HOAs | Scoopy Doo', 'How many pet waste stations a Chattanooga apartment community or HOA needs, where to place them, what scheduled servicing includes, and how commercial pricing is quoted.'],
  '/blog/how-to-get-rid-of-dog-poop-smell-in-yard-chattanooga': ['How to Get Rid of Dog Poop Smell in a Chattanooga Yard | Scoopy Doo', 'Why a Chattanooga yard still smells after you scoop, what actually clears it (remove, then soak), and when a $20 deodorizing treatment is worth paying for.'],
  '/blog/yard-cleanup-before-a-party-chattanooga': ['One-Time Yard Cleanup Before a Party in Chattanooga and North Georgia | Scoopy Doo', 'Hosting a cookout or graduation? One-time dog poop cleanups start at $85. How far ahead to book, what gets done, and how to handle yard smell in summer humidity.'],
  '/blog/new-puppy-pet-waste-removal-chattanooga': ['New Puppy Owner Guide: Pet Waste Cleanup in Chattanooga | Scoopy Doo', 'Bringing home a new puppy in Chattanooga? Here is how to set up a pet waste cleanup routine, why it matters for house training and health, and what professional service costs.'],
  '/blog/dog-poop-removal-north-georgia': ["Dog Poop Removal in Ringgold, Fort Oglethorpe and North Georgia | Scoopy Doo", "Scoopy Doo provides dog poop removal in Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA. Weekly service from $20 per visit, no contracts required."],
'/blog/yard-cleanup-before-selling-home-chattanooga': ["Do You Need to Clean Up Dog Waste Before Selling Your Chattanooga Home? | Scoopy Doo", "Selling a home in Chattanooga? Here is why yard cleanup and pet waste removal matter before listing photos and showings, plus a pre-listing checklist and pricing."],
};

const gaLocations = new Set(['ringgold','rossville','flintstone','fort-oglethorpe']);
const locationPages = [
  'chattanooga','hixson','red-bank','signal-mountain','ooltewah','east-brainerd',
  'soddy-daisy','apison','collegedale','highland-park','downtown',
  'east-ridge','lookout-mountain',
  'st-elmo','north-chattanooga','southside','lookout-valley','riverview','normal-park','brainerd',
  'ringgold','rossville','flintstone','fort-oglethorpe'
];
locationPages.forEach(function(loc) {
  var city = loc.split('-').map(function(w){return w[0].toUpperCase()+w.slice(1);}).join(' ');
  var state = gaLocations.has(loc) ? 'GA' : 'TN';
  routes['/service/' + loc] = [
    'Dog Poop Removal ' + city + ' ' + state + ' | Scoopy Doo',
    'Professional pet waste removal in ' + city + ', ' + state + '. Weekly & every-other-week pooper scooper service. Get your free quote today.'
  ];
});

// Neighborhood pages whose generated title/description would not match the page.
routes["/service/st-elmo"] = ["Dog Poop Removal in St. Elmo, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in St. Elmo, Chattanooga. Weekly and every-other-week dog poop pickup for historic homes at the foot of Lookout Mountain. Free quote."];
routes["/service/north-chattanooga"] = ["Dog Poop Removal in North Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in North Chattanooga and the Northshore. Weekly dog poop pickup near Frazier Avenue and Coolidge Park. No contracts - get a free quote."];
routes["/service/southside"] = ["Dog Poop Removal on the Southside, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal on Chattanooga's Southside. Dog poop pickup for Main Street district homes, lofts, courtyards, and small urban yards. Free online quote."];
routes["/service/lookout-valley"] = ["Dog Poop Removal in Lookout Valley, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in Lookout Valley, Chattanooga. Weekly and one-time dog waste cleanup for larger valley lots. No contracts - free quote online."];
routes["/service/riverview"] = ["Dog Poop Removal in Riverview, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in Riverview, Chattanooga. Discreet weekly dog waste pickup for established riverfront-area homes and larger lawns. Free quote."];
routes["/service/normal-park"] = ["Dog Poop Removal in Normal Park, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in Normal Park, Chattanooga. Family-friendly weekly dog waste pickup so kids and pets can use the yard safely. Free online quote."];
routes["/service/brainerd"] = ["Dog Poop Removal in Brainerd, Chattanooga | Scoopy Doo Pet Waste Removal", "Pet waste removal in Brainerd, Chattanooga. Weekly dog poop pickup for the flat, open yards common along the Brainerd Road corridor. Free quote."];

// Per-route social share image. Routes not listed here keep the site default
// og:image from index.html. Crawlers read this static HTML, not the React app,
// so a route needs an entry here for its link preview to differ.
const IMAGES = {
  '/doggy-doors': { url: 'https://www.scoopychatt.com/images/doggy-doors-hero.jpg', w: 1376, h: 768, alt: 'Dog using a professionally installed Scoopy Doo Doggy Door with app-controlled smart collar access.' }
};

// Replacement values are passed through a function rather than a '$1...$2' string:
// a value containing a dollar figure like "$20 per visit" would otherwise be read
// as a capture-group reference and mangle the tag (it turned "$20" into '"0').
function setAttr(html, pattern, value) {
  return html.replace(pattern, function (m, before, after) { return before + value + after; });
}

function injectMeta(html, title, desc, canonical, staticHtml, schemaHtml, image) {
  var result = html.replace(/<title>[^<]*<\/title>/, function () { return '<title>' + title + '<\/title>'; });
  result = setAttr(result, /(<meta name="description" content=")[^"]*(")/, desc);
  result = setAttr(result, /(<link rel="canonical" href=")[^"]*(")/, canonical);
  result = setAttr(result, /(<meta property="og:title" content=")[^"]*(")/, title);
  result = setAttr(result, /(<meta property="og:description" content=")[^"]*(")/, desc);
  result = setAttr(result, /(<meta property="og:url" content=")[^"]*(")/, canonical);
  result = setAttr(result, /(<meta name="twitter:title" content=")[^"]*(")/, title);
  result = setAttr(result, /(<meta name="twitter:description" content=")[^"]*(")/, desc);
  if (image) {
    result = setAttr(result, /(<meta property="og:image" content=")[^"]*(")/, image.url);
    result = setAttr(result, /(<meta property="og:image:width" content=")[^"]*(")/, image.w);
    result = setAttr(result, /(<meta property="og:image:height" content=")[^"]*(")/, image.h);
    result = setAttr(result, /(<meta property="og:image:alt" content=")[^"]*(")/, image.alt);
    result = setAttr(result, /(<meta name="twitter:image" content=")[^"]*(")/, image.url);
  }
  if (staticHtml) {
    result = result.replace(BODY_CLOSE, '<div id="scoopy-content" style="display:none" aria-hidden="true">' + staticHtml + DIV_CLOSE + BODY_CLOSE);
  }
  if (schemaHtml) {
    result = result.replace('</head>', schemaHtml + '</head>');
  }
  return result;
}

var count = 0;

// --- GEO schema injection (added) ---
var FAQ_PAIRS = [
  ["How do I schedule pet waste removal service?","Request a free quote at scoopychatt.com/quote with your yard details and number of dogs. We respond the same day and most new customers start within 2 to 5 days."],
  ["Does Scoopy Doo serve North Georgia?","Yes. We serve Ringgold, Rossville, Fort Oglethorpe, and Flintstone GA along with Chattanooga and surrounding Tennessee areas, with no extra charge for North Georgia service."],
  ["Is there a contract or long-term commitment?","No. Scoopy Doo never requires a contract. You can pause, reschedule, or cancel anytime with no cancellation fees."],
  ["How much does dog poop removal cost in Chattanooga?","Weekly service is $20 per visit for the first dog, twice-weekly is $18, and every-other-week is $33. Additional dogs add $2 per visit on weekly, $1 on twice-weekly, and $3 on every-other-week. One-time cleanups start at $85 covering up to three dogs, with $15 per dog beyond three, and include haul-away. Waste takeaway on recurring plans is $5 per visit and yard deodorizing is $20 per visit. Pricing is per visit and billing is monthly, with no contracts. Use the cost calculator at scoopychatt.com/cost-calculator or request a free quote for an exact price."],
  ["How often should I have my yard cleaned?","Weekly service is the most popular and keeps your yard consistently clean and safe. Homes with multiple dogs or heavy use often choose twice-weekly, while every-other-week works for lighter needs."],
  ["What happens on each visit?","You get an on-the-way text before we arrive, a full grid-pattern sweep of your entire yard, all waste double-bagged into your outdoor bin, and a gate photo confirmation when we finish. Waste takeaway, where we haul the bags off the property instead, is $5 per visit."],
  ["Do you offer one-time cleanups?","Yes. One-time yard cleanups are great for spring cleaning, move-outs, or before an event, and a good way to start fresh before beginning recurring service."],
  ["Do you handle commercial and HOA properties?","Yes. Scoopy Doo provides pet waste removal for apartments, HOAs, dog parks, and shared common areas with flexible scheduling and no contracts. Pet waste stations are $299 per station installed and $10 per station per week to service."],
  ["Do you offer yard deodorizing?","Yes. Deodorizing and sanitizing is $20 per visit. It neutralizes the odor compounds and bacteria left in the soil after the waste itself is removed, and it can be added to any recurring plan or to a one-time cleanup."]
];
function ldScript(obj){return '<script type="application/ld+json">'+JSON.stringify(obj)+'</'+'script>';}
function faqSchema(pairs){var items=[];for(var i=0;i<pairs.length;i++){items.push({"@type":"Question","name":pairs[i][0],"acceptedAnswer":{"@type":"Answer","text":pairs[i][1]}});}return {"@context":"https://schema.org","@type":"FAQPage","mainEntity":items};}
function titleCaseSlug(slug){return slug.split("-").map(function(w){return w.charAt(0).toUpperCase()+w.slice(1);}).join(" ");}
var HOME_FAQ_PAIRS=[["What is Scoopy Doo and what does the service include?","Scoopy Doo LLC is Chattanooga's locally owned dog poop removal and pooper scooper service. Every visit includes a full grid-pattern yard sweep, all waste double-bagged into your outdoor bin, gate closure, and a photo confirmation sent to you. No contracts - cancel or change anytime."],["How does Scoopy Doo pet waste removal work?","It's simple: request a free quote online, we send you pricing based on yard size and number of dogs, and you pick a schedule. We show up on your day, text you when we're on the way, clean the entire yard, close your gate, and send a photo when done. Payment is handled online - no checks, no phone tag."],["Do you offer a scoopy poopy service near Chattanooga, TN?","Yes - Scoopy Doo provides professional pooper scooper and scoopy poopy service throughout the Chattanooga metro including Hixson, Red Bank, Signal Mountain, Ooltewah, East Brainerd, Lookout Mountain, Soddy-Daisy, and North Georgia communities like Ringgold, Rossville, and Fort Oglethorpe."],["How often should I schedule dog waste removal?","Weekly service is our most popular option and works well for most one- or two-dog households. We also offer 2x weekly service for high-traffic yards and multiple dogs, every-other-week for lower-use yards, and one-time cleanups if you need to start fresh before beginning a regular schedule."],["Is Scoopy Doo dog waste removal safe for kids and pets?","Yes. We sanitize all scooping equipment between every yard to prevent cross-contamination. We never use harmful chemicals in your yard, and all waste is double-bagged into your bin, with haul-away off the property available for $5 per visit. A clean yard is a safer yard - dog waste carries bacteria and parasites that are hazardous to children and other animals."],["How much does pooper scooper service cost in Chattanooga?","Weekly service is $20 per visit for the first dog, twice-weekly is $18, and every-other-week is $33. Additional dogs add $2 per visit on weekly, $1 on twice-weekly, and $3 on every-other-week. One-time cleanups start at $85 with haul-away included. On recurring plans, waste takeaway is $5 per visit and yard deodorizing is $20 per visit. Scoopy Doo prices per visit and bills monthly, with no contracts and no cancellation fees. Free quotes at scoopychatt.com/quote."],["Do you service HOAs and apartment communities?","Yes. We service HOA common areas, dog-walking paths, and pet waste stations in addition to individual residential homes. We can invoice HOA boards directly and maintain visit records for compliance documentation."]];
function routeSchema(route){
  var base="https://www.scoopychatt.com";
  if(route==="/"){return ldScript(faqSchema(HOME_FAQ_PAIRS));}if(route==="/press"){var col={"@context":"https://schema.org","@type":"CollectionPage","name":"Scoopy Doo in the News","url":base+"/press","description":"News coverage and press mentions of Scoopy Doo LLC, the largest pet waste removal company in the Chattanooga TN area.","about":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","url":base,"telephone":"+1-423-600-5040"}};var art={"@context":"https://schema.org","@type":"NewsArticle","headline":"14-Year-Old Entrepreneur Builds Chattanooga Largest Pet Waste Removal Company In Under A Year","url":"https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx","datePublished":"2026-06-23","image":"https://images.chattanoogan.com/2026/6/article.520251.jpg","publisher":{"@type":"Organization","name":"Chattanoogan.com","url":"https://www.chattanoogan.com"},"about":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","url":base},"mainEntityOfPage":"https://www.chattanoogan.com/2026/6/23/520251/14-Year-Old-Entrepreneur-Builds.aspx"};return ldScript(col)+ldScript(art);}if(route==="/faq"){return ldScript(faqSchema(FAQ_PAIRS));}
  if(route.indexOf("/service/")===0){
    var slug=route.slice(9);
    var d=(typeof LOC!=="undefined")?LOC[slug]:null;
    if(!d){return "";}
    var city=titleCaseSlug(slug);
    var svc={"@context":"https://schema.org","@type":"Service","serviceType":"Pet waste removal","name":"Dog Poop Removal in "+city,"description":d.desc,"url":base+route,"areaServed":{"@type":"City","name":city},"provider":{"@type":"LocalBusiness","name":"Scoopy Doo LLC","telephone":"+1-423-600-5040","url":base,"priceRange":"$$"}};
    var out=ldScript(svc);
    if(d.faqs&&d.faqs.length){out+=ldScript(faqSchema(d.faqs));}
    return out;
  }
  return "";
}
// --- end GEO schema injection ---

for (var route in routes) {
  var parts = routes[route];
  var title = parts[0];
  var desc = parts[1];
  var canonical = BASE + route;
  var locSlug = route.startsWith('/service/') ? route.replace('/service/', '') : null;
  var staticHtml = SC[route] || (locSlug ? makeLocContent(locSlug) : '');
  var schemaHtml = SCHEMA[route] || '';
  var html = injectMeta(template, title, desc, canonical, staticHtml, schemaHtml, IMAGES[route]);
  var dirPath = path.join(distDir, route);
  fs.mkdirSync(dirPath, { recursive: true });
  var __s = routeSchema(route); if (__s) { html = html.replace("</head>", __s + "</head>"); }
      fs.writeFileSync(path.join(dirPath, 'index.html'), html);
  count++;
}
console.log('SEO inject complete: ' + count + ' pages.');
} catch(e) {
  console.error('SEO inject warning:', e.message);
  process.exit(0);
}
